### ISSUE TITLE
Etcd discovery domain doesn't work with plain Kubernetes

### ISSUE THREAD

**Issue by jberkus** [zalando/spilo#100]
Attempting to set the ETCD_DISCOVERY_DOMAIN to an etcd service on Kubernetes without helm results in etcd not working.  

2016-11-06 07:43:05,803 INFO: waiting on etcd
2016-11-06 07:43:10,817 ERROR: Can not resolve SRV for etcd.default.svc.cluster.local
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/patroni/dcs/etcd.py", line 150, in get_srv_record
    return [(str(r.target).rstrip('.'), r.port) for r in resolver.query('_etcd-server._tcp.' + host, 'SRV')]
  File "/usr/local/lib/python3.4/dist-packages/dns/resolver.py", line 1068, in query
    raise_on_no_answer, source_port)
  File "/usr/local/lib/python3.4/dist-packages/dns/resolver.py", line 995, in query
    raise NXDOMAIN(qname=qnames_to_try)
dns.resolver.NXDOMAIN: None of DNS query names exist: ['_etcd-server._tcp.etcd.default.svc.cluster.local.', '_etcd-server._tcp.etcd.default.svc.cluster.local.default.svc.cluster.local.', '_etcd-server._tcp.etcd.default.svc.cluster.local.svc.cluster.local.', '_etcd-server._tcp.etcd.default.svc.cluster.local.cluster.local.', '_etcd-server._tcp.etcd.default.svc.cluster.local.us-west-2.compute.internal.']

I also tried setting ETCD_HOST instead, but that resulted in patroni not starting at all:

2016-11-06 08:00:45,833 INFO spawned: 'pgq' with pid 33
Usage: /usr/local/bin/patroni config.yml
	Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2016-11-06 08:00:46,019 INFO exited: patroni (exit status 1; not expected)
2016-11-06 08:00:47,020 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-11-06 08:00:47,021 INFO spawned: 'patroni' with pid 39
2016-11-06 08:00:47,021 INFO success: pgq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Usage: /usr/local/bin/patroni config.yml
	Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable

I suspect the latter is due to quoting with the : in the etcd host name, but due to the value pass-through, it's not really fixable in the Kube file.

**Comment by jberkus** [comment]
Oh, and attaching a config:

apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: patroni
  labels:
    component: patroni-patroni
spec:
  serviceName: patroni
  replicas: 3
  template:
    metadata:
      name: patroni
      labels:
        component: patroni-patroni
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: spilo
        image: registry.opensource.zalan.do/acid/spilo-9.5:1.1-p5
        env:
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-superuser
        - name: PGPASSWORD_ADMIN
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-admin
        - name: PGPASSWORD_STANDBY
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-standby
        - name: SCOPE
          value: cluster01
        - name: USE_WALE
          value: false
        - name: PGROOT
          value: /home/postgres/pgdata/pgroot
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ETCD_DISCOVERY_DOMAIN
          value: etcd.$(POD_NAMESPACE).svc.cluster.local
        ports:
        - containerPort: 8008
        - containerPort: 5432
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: pgdata
          mountPath: /home/postgres/pgdata
        - mountPath: /etc/patroni
          name: patroni-config
          readOnly: true
      volumes:
      - name: patroni-config
        secret:
          secretName: patroni
      - name: pgdata
        emptyDir: {}

**Comment by alexeyklyukin** [comment]
Indeed,  in the case of a ETCD_DISCOVERY_DOMAIN Patroni expects to find an SRV record.
In the case of an ETCD_HOST, the expected value should be the hostname:port, as listed here:
https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst

So it should be able to work once you add :2379 to the value, assuming you run Etcd with a default client port.

**Comment by jberkus** [comment]
Oh, the problem with ETCD_HOST is escaping the ":".  You have to put it in as:

```
etcd.svc.cluster.local\:2379
```
... for it to work.

**Comment by alexeyklyukin** [comment]
Hm, no, it actually worked for me as is, without escapes. I'll take a look whether we need to process them in Spilo.

**Comment by PetrGlad** [comment]
This  says something about having named  ports in service records... 
http://kubernetes.io/docs/user-guide/services/#dns

**Comment by jberkus** [comment]
Alexey:

Huh.  Because I got a YAML parse error until I escaped the :

**Comment by gdmello** [comment]
Was about to open an issue for this error, when using `Etcd.discovery` when i stumbled across this issue. What is the status?

The README indicates the value of `Etcd.discovery` should be `<release-name>-etcd.<namespace>.svc.cluster.local`, assuming release name is the from Helm.

```
$ helm ls
NAME             	REVISION	UPDATED                 	STATUS  	CHART              	NAMESPACE
excited-greyhound	2       	Wed Sep  6 15:21:07 2017	DEPLOYED	etcd-operator-0.4.3	default  
knotted-wallaby  	1       	Wed Sep  6 16:02:57 2017	DEPLOYED	patroni-0.3.2      	default  
```

Patroni [expects](https://github.com/zalando/patroni/blob/856a13e24c9e81fa23857e69a0434b34b771bb2f/patroni/dcs/etcd.py#L221) to find the etcd members off this SRV record-
```python
Fetch list of etcd-cluster member by resolving _etcd-server._tcp. SRV record.
```
However, this SRV record spilo expects isn't present-
```
$ kubectl run -i --tty ubuntu --image=ubuntu --restart=Never -- sh
# dig +noall +answer @10.3.0.10 _etcd-server._tcp.excited-greyhound SRV
# 
```

Even trying with the service name, get the same error-
```
$ kc get svc
NAME                                  CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
etcd-cluster-patroni                  None         <none>        2380/TCP            22h
etcd-cluster-patroni-backup-sidecar   10.3.0.207   <none>        19999/TCP           22h
etcd-cluster-patroni-client           10.3.0.7     <none>        2379/TCP            22h
```

```
$ kubectl run -i --tty ubuntu --image=ubuntu --restart=Never -- sh
# dig +noall +answer @10.3.0.10 etcd-cluster-patroni.default.svc.cluster.local SRV
etcd-cluster-patroni.default.svc.cluster.local.	30 IN SRV 10 33 0 etcd-cluster-patroni-0002.etcd-cluster-patroni.default.svc.cluster.local.
etcd-cluster-patroni.default.svc.cluster.local.	30 IN SRV 10 33 0 etcd-cluster-patroni-0001.etcd-cluster-patroni.default.svc.cluster.local.
etcd-cluster-patroni.default.svc.cluster.local.	30 IN SRV 10 33 0 etcd-cluster-patroni-0000.etcd-cluster-patroni.default.svc.cluster.local.
```

Is there a workaround? I'm going to try out `Etcd.host`, even though the docs indicate
> not used (Etcd.Discovery is used instead)

**Comment by CyberDem0n** [comment]
> Patroni expects to find the etcd members off this SRV record

I've been assuming that cluster discovery using SRV records should be done as it described here: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md#dns-discovery

If there are such records (_etcd-server._tcp, _etcd-client._tcp, _etcd-server-ssl._tcp, _etcd-client-ssl._tcp) in DNS available, etcd proxy for example can use them correctly for cluster discovery. Patroni acts similarly.

Actually there is no preferred way of specifying Etcd cluster in Patroni.
ETCD_HOST https://github.com/zalando/spilo/blob/master/postgres-appliance/configure_spilo.py#L340 will also work without any problem.

In fact, for our deployments on EC2 instances on AWS we are using ETCD_DISCOVERY_DOMAIN and for deployment in Kubernetes we are using ETCD_HOST

**Comment by CyberDem0n** [comment]
And one more thing.
May be it would be interesting for you to try https://github.com/zalando/patroni/tree/feature/k8s/kubernetes from https://github.com/zalando/patroni/pull/500
It doesn't require you to run etcd. Patroni can use Kubernetes API for a leader elections and keeping cluster state.

Just build docker image and use [manifest](https://github.com/zalando/patroni/blob/feature/k8s/kubernetes/patroni_k8s.yaml) to deploy it.

**Comment by gdmello** [comment]
> I've been assuming that cluster discovery using SRV records should be done as it described here: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md#dns-discovery

Great work @CyberDem0n! I wish this were documented in the README. Moreover, the documentation states the default value for `Etcd.discovery` is `<release-name>-etcd.<namespace>.svc.cluster.local`, which i don't think is correct, rather it should be `_etcd-server-ssl._tcp.example.com`, where 'example.com' is set in `-discovery-srv` flag to etcd.
