### ISSUE TITLE
Readme rewrite draft: link

### ISSUE THREAD

**Issue by LappleApple** [zalando/spilo#131]
Hey @alexeyklyukin @CyberDem0n, I've begun creating a simple README for the next iteration of Spilo [here](https://github.com/LappleApple/spilo/blob/master/README.md).

It wasn't clear from the current Spilo README+ Read the Docs that Spilo was a Docker image; sometimes it's important to state the obvious. Even Docker images on the Docker hub say "this Docker image." With this in mind, I've added the obvious. :)

I've also drawn upon the standard text of the official Postgres Docker image and other DB-related Docker images at the Docker Hub, to brainstorm section headings for you to consider adding to your README. Feel free to discard what's irrelevant. My advice is to just keep simple whatever is essential and not subject to change with Spilo Phase II. 

Speaking of which: I realize that Spilo's undergoing transformation, and that the postgres-operator's in progress. You might drop some lines about the operator inside Spilo's readme, to share your project vision more openly. This might then inspire feedback from others in the community, who will be curious as well as insightful.

**Comment by alexeyklyukin** [comment]
Thanks, would you make it a PR?

**Comment by LappleApple** [comment]
@alexeyklyukin Sure, though there are a lot of open/proposed sections. Just want to make sure that you saw those; the README is quite incomplete, still. :)

**Comment by alexeyklyukin** [comment]
Yes, I saw it. For me It's easier to add inline comments to the PR, rather than commenting here with references to the specific lines.
