### ISSUE TITLE
Etcd appliance: multiple stack creations possible with same STACK_VERSION

### ISSUE THREAD

**Issue by vosmann** [zalando/spilo#14]
Hello,
I've noticed that it's possible to create multiple stacks with the same stack version (e.g. "etcd1") using etcd-cluster.yaml. This is strange since usually `senza` does not allow this.

The main point here is that _after_ creating and deleting a cluster with the same version "etcd1", trying to list instances or events will result in an empty output. 
Basically, running `senza instances etcd-cluster.yaml etcd1` or `senza events etcd-cluster.yaml etcd1` will result in nothing being shown. As if there is no cluster online with stack version "etcd1".

**Comment by feikesteenbergen** [comment]
I don't fully understand the issue

* (StackName, version) has to be unique, perhaps the StackName differed?
* empty output: It is what I expect from senza if nothing is defined
* you say you deleted it, therefore it makes sense that nothing is shown
* This might be better addressed by raising this issue at github.com/zalando-stups/senza
