### ISSUE TITLE
Tag EBS volume with Name early

### ISSUE THREAD

**Issue by a1exsh** [zalando/spilo#141]
Currently tagging of a new EBS volume with Name seems to happen only after base backup is finished to be streamed.  This makes it harder to monitor performance of the EBS using Amazon Web console or any other tools where you would filter the volumes by Name tag.

**Comment by alexeyklyukin** [comment]
Hm.. the tagging is currently done by Patroni, that does tags on role change. I think it's a good idea to do tagging on start as well.
