### ISSUE TITLE
Missing file scm-source.json file

### ISSUE THREAD

**Issue by zafinxueqian** [zalando/spilo#168]
In Dokcerfile , line 161, where is scm-source.json file??

**Comment by evaldasou** [comment]
I had the same issue... I just removed that line and image was build successfully.
However, maybe it's required and something will not work?

**Comment by evaldasou** [comment]
Not sure if related... but only difference between my image (build from Dockerfile in this repository , and original one is ):

Original:
`Selector:		<none>
Type:			ClusterIP
IP:			10.111.252.229
Port:			<unset>	5432/TCP
Endpoints:		10.108.0.125:5432
`

Build from docker file in this repo:
`Selector:		<none>
Type:			ClusterIP
IP:			10.111.241.133
Port:			<unset>	5432/TCP
Endpoints:		`

Looks it does not expose Endpoint IP automatically... not sure how it could happen.
If I type` helm status postgres` , - I see Endpoint IP for both deployments.

**Comment by zafinxueqian** [comment]
Hi @evaldasou , so you can run spilo with the changed spilo image?

**Comment by CyberDem0n** [comment]
scm-source.json is created by https://github.com/zalando/spilo/blob/master/postgres-appliance/build.sh

Also you can put an empty file there. It doesn't required for spilo & patroni to work.

I am not sure about helm package. Was it updated to use `StatefulSets`?
Also in kubernetes-1.6 there were some changes regarding `Services` and `Endpoints` kinds. 
What kubernetes version do you run?

`Serice.Endpoins` is managed by the master `Pod`. When postgres is started as a master or promoted to the master, Patroni will call a callback script: https://github.com/zalando/spilo/blob/master/postgres-appliance/callback_role.py

It should update `Endpoints` object in kubernetes. Do you see any errors in the logs?
```
$ kubectl logs master-pod-name-X
```

Can you please try to run /callback_role.py script manually?
```
$ kubectl exec -ti master-pod-name-X bash
$ /callback_role.py on_role_change master <cluster-name>
```

cluster-name should match with the `StatefulSet`, `Service` and `Endpoints` name.

**Comment by evaldasou** [comment]
Thanks for quick response @CyberDem0n !
So in Dockerfile I used, I have changed nothing, except I have added one command to install postgis extension with apt-get command.

I am using this helm chart : https://github.com/kubernetes/charts/tree/master/incubator/patroni

I am not sure what is missing,  cluster actually does not work (I cannot use it) (because Endpoint IP address is not exposed to the service). I have ran /callback_role.py script, - but nothing happens, no output and no change in the cluster. I have also tried to delete master pod, another pod takes the role - but Endpoint IP is still not updated. 

What else could I try? 

Thanks a lot!

**Comment by evaldasou** [comment]
By the way , I am running kubernetes 1.6.2. However, @CyberDem0n everything works with Your default image... but I do not see Endpoint exposed once I add installation for : postgresql-${version}-postgis-scripts

That's all I have did!

**Comment by hjacobs** [comment]
@evaldasou did you check out our Kubernetes PostgreSQL Operator already? :point_right: https://github.com/zalando-incubator/postgres-operator

**Comment by evaldasou** [comment]
thanks @hjacobs ! 
However, I wanted to use helm and that chart from incubator project... maybe You guys have older dockerfile for this image:
`Image: registry.opensource.zalan.do/acid/spilo-9.6
  Version: 1.2-p13` ?

As I checked with newer image:
`  Image: registry.opensource.zalan.do/acid/spilo-9.6
  Version: 1.2-p26`
I am not getting Endpoints IPs either. Something has changed :)
I just need older Dockerfile!

**Comment by CyberDem0n** [comment]
I think it doesn't work due to https://github.com/zalando/spilo/commit/2be341ab026cef81982ca55b4328ea60aecb13f8

What version of kubernetes are running on?

**Comment by evaldasou** [comment]
@CyberDem0n I'm using 1.6.2

**Comment by evaldasou** [comment]
with `helm status postgres` it's visible:

> LAST DEPLOYED: Tue May 30 20:00:14 2017
> NAMESPACE: prod
> STATUS: DEPLOYED
> 
> RESOURCES:
> ==> v1/Service
> NAME              CLUSTER-IP    EXTERNAL-IP  PORT(S)            AGE
> postgres-patroni  10.111.244.7  <none>       5432/TCP           1h
> postgres-etcd     None          <none>       2380/TCP,2379/TCP  1h
> 
> ==> v1beta1/StatefulSet
> NAME              DESIRED  CURRENT  AGE
> postgres-etcd     3        3        1h
> postgres-patroni  3        3        1h
> 
> ==> v1/Endpoints
> NAME              ENDPOINTS          AGE
> postgres-patroni  10.108.0.154:5432  1h

but not with : `kubectl describe svc postgres-patroni --namespace prod`

> Name:			postgres-patroni
> Namespace:		prod
> Labels:			chart=patroni-0.2.0
> 			component=postgres-patroni
> 			heritage=Tiller
> 			release=postgres
> Annotations:		<none>
> Selector:		<none>
> Type:			ClusterIP
> IP:			10.111.244.7
> Port:			<unset>	5432/TCP
> Endpoints:		
> Session Affinity:	None
> Events:			<none>

**Comment by evaldasou** [comment]
hey @CyberDem0n  , I just checked [2be341a](https://github.com/zalando/spilo/commit/2be341ab026cef81982ca55b4328ea60aecb13f8) and with old settings script updates and exposes Endpoint correctly.

This is what I see now :+1:  : 

> Port:			<unset>	5432/TCP
> Endpoints:		10.108.0.154:5432
>

As We see Port is unset, but at least it works like before :) . Something is missing in another part of the script probably. Thanks!

**Comment by hjacobs** [comment]
The original issue was about `scm-source.json` and that was answered (it's generated by https://github.com/zalando/spilo/blob/master/postgres-appliance/build.sh). Closing.
