### ISSUE TITLE
ISO C90 forbids variable length array 'ct' [-Wvla] issue

### ISSUE THREAD

**Issue by ygxue** [zalando/spilo#170]
Hi, I tried to run docker build of the " spilo/postgres-appliance/Dockerfile", and got an error as below.

pam_oauth2.c: In function 'pam_sm_authenticate':
pam_oauth2.c:195:12: warning: ISO C90 forbids variable length array 'ct' [-Wvla]
struct check_tokens ct[argc];

My system is CentOS 7. 
Any suggestion would be appreciate.

**Comment by CyberDem0n** [comment]
Hi @ygxue,

this is just warning, you can ignore it.
It doesn't stop the build process.

**Comment by ygxue** [comment]
Hi @CyberDem0n ,

It doesn't stop the build process. 
Will it affect the function of the image? Thanks!

**Comment by CyberDem0n** [comment]
> Will it affect the function of the image?

No
