### ISSUE TITLE
Disable Etcd

### ISSUE THREAD

**Issue by joe-pll** [zalando/spilo#190]
Hi, first of all thanks for your work, it's truly amazing.

I was trying to disable etcd (save some resources), since I set the variable ETCD_HOST, but i could not find any option to do such a thing.  
I read the **configure_spilo.py** and I saw that creating an empty **etcd.conf** file in supervisord it should not overwrite it unless when the option **--force** is specified.  
I found out it was overwriting the file anyway, even if existing. I searched for the function **write_file** and apparently after dumping the warning, does not skip the writing part

```python
def write_file(config, filename, overwrite):
    if not overwrite and os.path.exists(filename):
        logging.warning('File {} already exists, not overwriting. (Use option --force if necessary)'.format(filename))
    with open(filename, 'w') as f:
        logging.info('Writing to file {}'.format(filename))
        f.write(config)
```

So in the log I have  
```
pg1_1  | 2017-09-27 09:54:44,887 - bootstrapping - WARNING - File /etc/supervisor/conf.d/etcd.conf already exists, not overwriting. (Use option --force if necessary)
pg1_1  | 2017-09-27 09:54:44,888 - bootstrapping - INFO - Writing to file /etc/supervisor/conf.d/etcd.conf
```

The version of Spilo I've been using is the `spilo-9.6:1.2-p27`.

**Comment by CyberDem0n** [comment]
Hi @joe-pll,

configure_spilo.py tries to detect you environment (aws, gce, openstack, kubernetes). In case if it is something different, it assumes that you just start it in a docker container on your local machine and creates etcd.conf: https://github.com/zalando/spilo/blob/master/postgres-appliance/configure_spilo.py#L517 for supervisor.

You are actually right, if there is either `ETCD_HOST` or `ETCD_DISCOVERY_DOMAIN` environment variables set, configure_spilo.py should not create etcd.conf
Can you please create a PR fixing it?

And one more question, can you explain a little bit more about your setup? I am just curios, where and how do you run Spilo?

**Comment by joe-pll** [comment]
Hi @CyberDem0n,

sorry for my late answer, I was quite busy last period. I will make a PR with the fix.
I am using Spilo both with Kubernetes and with 3 different instances of docker-compose (running on 3 different hosts). I need Postgres as a backend for Kong gateway with replication and self election. Furthermore I use HAProxy to point the Postgres' master, using a check on Patroni's port.

Kong instances will point to HAProxy.

**Comment by hjacobs** [comment]
@joe-pll as you mentioned Kubernetes: please also check out our Postgres Operator for Kubernetes (it uses Patroni under the hood), we are currently migrating first production databases to it :tada:  :point_right: https://github.com/zalando-incubator/postgres-operator

**Comment by joe-pll** [comment]
Thanks @hjacobs, the project looks great. I will test it on my k8s cluster.
