### ISSUE TITLE
Custom PGDATA directory not working.

### ISSUE THREAD

**Issue by michailbrynard** [zalando/spilo#200]
When running the container locally with the default settings, everything seems ok. However when I update the environmental variables, `PGHOME=/var/lib/postgresql`, `PGROOT=/var/lib/postgresql/data` and `PGDATA=/var/lib/postgresql/data/pgdata`, Patroni fails with the following error:
```
2017-12-18 14:22:10,483 INFO spawned: 'patroni' with pid 53
2017-12-18 14:22:10,484 INFO success: pgq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Usage: /usr/local/bin/patroni config.yml
postgres_1  |   Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2017-12-18 14:22:10,744 INFO exited: patroni (exit status 1; not expected)
2017-12-18 14:22:12,755 INFO spawned: 'patroni' with pid 55
Usage: /usr/local/bin/patroni config.yml
postgres_1  |   Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2017-12-18 14:22:12,984 INFO exited: patroni (exit status 1; not expected)
2017-12-18 14:22:15,996 INFO spawned: 'patroni' with pid 57
Usage: /usr/local/bin/patroni config.yml
postgres_1  |   Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2017-12-18 14:22:16,240 INFO exited: patroni (exit status 1; not expected)
2017-12-18 14:22:17,247 INFO gave up: patroni entered FATAL state, too many start retries too quickly
```

**Comment by cbandy** [comment]
Last I checked, those variables affect how the container is built:
https://github.com/zalando/spilo/blob/7516aff6565b41b9f38840f696a563e8f87c34ad/postgres-appliance/Dockerfile#L164-L185

To be clear, are you *building* the container (`docker build`) with those variables and/or *running* (`docker run`) with them?

**Comment by michailbrynard** [comment]
Ah ok, I didn't realize that. I was testing with the registry.opensource.zalan.do/acid/spilo-9.5 image.

**Comment by kwiesmueller** [comment]
We are getting the exact same errors in our setup and can't figure out why.
Sometimes it works but sometimes fresh setups end up like this.

**Comment by michailbrynard** [comment]
@kwiesmueller Are you also trying to run spilo with a custom PGDATA environmental variable set when you get the error and if so, are you building the container with the same PGDATA value as @cbandy suggested?

**Comment by kwiesmueller** [comment]
We did, but with the default value. As you can see above in my test the variables are not set and we are using official images.
