### ISSUE TITLE
Dockerfile.build error

### ISSUE THREAD

**Issue by stefanhipfel** [zalando/spilo#228]
Hi,

does anyone else have issues to build the docker image?
I am getting the following error when installing pg_repack
make -C pg_repack USE_PGXS=1 clean install
/usr/bin/ld: cannot find -lpgport
/usr/bin/ld: cannot find -lpgcommon

Suddenly pgport and common seem to be missing.

Thanks in advance

**Comment by stefanhipfel** [comment]
Issues has been opened at pg_repack: https://github.com/reorg/pg_repack/issues/179

**Comment by CyberDem0n** [comment]
It is not an issue with pg_repack, but rather with postgres packages.
Before the last release libpgcommon.a abd libpgport.a were installed into /usr/lib/x86_64-linux-gnu.
Now they are installed into /usr/lib/postgresql/${version}/lib, but `pg_config --libdir` still reports /usr/lib/x86_64-linux-gnu.

**Comment by CyberDem0n** [comment]
Ok, here is workaround: https://github.com/zalando/spilo/pull/229

**Comment by stefanhipfel** [comment]
U beat me to it. Thanks a lot!
