### ISSUE TITLE
Hardcoded patroni.yml template

### ISSUE THREAD

**Issue by mommys-little-hacker** [zalando/spilo#248]
I am currently trying to build custom patroni image with a few extensions. This implies adding some postgres.conf configuration directives into postgres.parameters in patroni.yml.

Since this file is autogenerated at container startup from a template, I need to change template directly in configure_spilo.py file. This means I have to manually keep my version of this script synced with upstream.

Is it possible to edit launch.sh to generate patroni.yml from template using envsubst from gettext-base package and remove it from configure_spilo.py?

**Comment by Legogris** [comment]
It does look like you can just template in your own config yaml file and reference it via either `SPILO_CONFIGURATION` or `PATRONI_CONFIGURATION` env vars: https://github.com/zalando/spilo/blob/c307996bea5a734481aebaf403aee31584aa366f/postgres-appliance/scripts/configure_spilo.py#L911
