### ISSUE TITLE
FEATURE REQUEST: Create DB when bringing initial cluster

### ISSUE THREAD

**Issue by mpritter76** [zalando/spilo#250]
#### NEW FEATURE REQUEST

Would be nice to have an option to instantiate a db when bringing up a new cluster. Current thoughts I had on it was to add a new program to supervisord (postgres-appliance/supervisor/conf.d/createpgdb.conf) that might look something like the following:
```
[program:createpgdb]
priority=1000
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
autorestart=false
autostart=false
startsecs=0
command=/scripts/createpgdb.sh
```

NEW SCRIPT: /scripts/createpgdb.sh
```
#!/bin/bash
set -e

PGUSER_SUPERUSER="${PGUSER_SUPERUSER:-postgres}"

until pg_isready --dbname postgres --username $PGUSER_SUPERUSER --host localhost
do
  echo "Waiting for postgres to come up..."
  sleep 2;
done

psql=( psql -v )

if [[ -n "$PG_DBNAME" && $PG_DBNAME != "postgres" ]]; then
  echo "Creating database ( $PG_DBNAME )..."
  "${psql[@]}" --username $PGUSER_SUPERUSER -d postgres <<-EOSQL
    CREATE DATABASE "$PG_DBNAME" ;
EOSQL
fi
```

In order to make this work an environment variable (PG_DBNAME) would have to be supplied with the name of the database you would like to have created.

Just looking for some thoughts on this.

**Comment by Jan-M** [comment]
This should be part of your application bootstrapping or some other mechanism, but not part of the supervisor flow imho.

Look at the Postgres operator for K8S. It also bootstraps databases and users.
