### ISSUE TITLE
Feature Request: SQL statement Logging

### ISSUE THREAD

**Issue by schmitch** [zalando/spilo#251]
it would be cool, if there would be a way to actually create and analyze postgresql logs directly in spilo.

i.e. add `pgbadger` and configs to the the image/cron to always generate pgbadger files. since spilo already has a http interface the files might be served over the interface as well.

**Comment by Jan-M** [comment]
-1 from me, should happen somewhere else.

If needed the infrastructure should support some kind of sidecar Docker that then takes care of additional features.
