### ISSUE TITLE
K8s template with Kubernetes as DCS not working

### ISSUE THREAD

**Issue by kmoppel** [zalando/spilo#265]
Hi guys!

Not sure if my own config issue (new to Kubernetes) or a real issue but the provided [template](
https://github.com/zalando/spilo/blob/master/kubernetes/spilo_kubernetes_aws.yaml) leaves the standby in failed state with quite a dry error message:

2018-09-27 07:41:09,233 INFO: Lock owner: zalandodemo01-0; I am zalandodemo01-1
2018-09-27 07:41:09,247 INFO: trying to bootstrap from leader 'zalandodemo01-0'
2018-09-27 07:41:09,248 ERROR: failed to bootstrap from leader 'zalandodemo01-0'
2018-09-27 07:41:09,248 INFO: Removing data directory: /home/postgres/pgdata/pgroot/data

They adjustments I made to the template:
Removed params - ETCD_HOST, WAL_S3_BUCKE, LOG_S3_BUCKET, BACKUP_SCHEDULE
Added params - DCS_ENABLE_KUBERNETES_API='true'
image: registry.opensource.zalan.do/acid/spilo-10:1.4-p16
serviceAccountName: default (gave cluster-admin priviliges beforehand)

Got the same error also in the KUBERNETES_USE_CONFIGMAPS mode.

And actually to get even so far had to give a new name to the declared Endpoint - otherwise it was erroring out with "HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \"zalandodemo01\" already exists","reason":"AlreadyExists","details":{"name":"zalandodemo01","kind":"endpoints"},"code":409}"

Used K8s: v1.10 on Minikube (tried also with GKE actually)

Any ideas / hints would be very welcome! And btw, is there a way to add some verbosity to the logs?

**Comment by CyberDem0n** [comment]
Hi @kmoppel,

this template seems to be very outdated, people usually use [helm chart](https://github.com/helm/charts/tree/master/incubator/patroni) to deploy spilo on k8s.

I'll try to prepare the new template.

One can add `PATRONI_LOGLEVEL=DEBUG` environment variable before starting Patroni and get more logs, but most of them are just communication between Patroni and DCS.

You can also look into Pod logs and postgres from the master, they should definitely have something.

**Comment by kmoppel** [comment]
@CyberDem0n  Thanks! Ah good to know. With last template edit 2 months ago thought it should work :) But yes Helm is not an option sadly for this concrete use case so a working template would be perfect.

On the master pod log there are no FATAL-s...so the standby probably has difficulties finding out the connect string. With some debug prints I tracked it down to [here](https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L683)...but no idea currently why it's empty

**Comment by Jan-M** [comment]
@CyberDem0n Lets remove the templates or update them?
