### ISSUE TITLE
Custom value of HUMAN_ROLE  not applied

### ISSUE THREAD

**Issue by zerg-junior** [zalando/spilo#274]
Setting [a PAM role name in the Postgres operator](https://github.com/zalando-incubator/postgres-operator/issues/407) results in the correct Spilo configuration, but the resultant `pg_hba` still contains the default `zalandos` value.

**Comment by cbandy** [comment]
Perhaps related to #245?

**Comment by zerg-junior** [comment]
Spilo expects the `HUMAN_ROLE` env var to be set separately; the patch for [the operator is here](https://github.com/zalando-incubator/postgres-operator/pull/409/files)

> Perhaps related to #245?

afaik this can fixed by configuring the `pg_hba` in the  `postgresql` section  of `SPILO_CONFIGURATION` instead of the `bootstrap` one (see relevant [Postgres operator patch](https://github.com/zalando-incubator/postgres-operator/issues/330#issuecomment-411338457))
