### ISSUE TITLE
Question: Is there an estimated timeline for official pg11 support?

### ISSUE THREAD

**Issue by valer-cara** [zalando/spilo#277]
Hey,

I tried to build a spilo image with pg11 by setting the PGVERSION variable, but ran in a cascading set of dependency issues so ultimately gave up.

Is there an estimated timeline for official pg11 support?

PS: i've been peeking around your [registry](https://registry.opensource.zalan.do/ui/#!/Pier_One_API/piertwo_api_custom_read_artifacts) and seen a `spilo-cdp-11` on team `acid` artifact that looked promising.

Thank you for all the work on Spilo!

**Comment by zerg-junior** [comment]
Hello, valer-cara

you can try the work-in-progress `feature/pg11` branch.

**Comment by Jan-M** [comment]
spilo-11:1.5-p2 includes Postgres 11.
