### ISSUE TITLE
Please add timescaledb to the list of shared_preload_libraries

### ISSUE THREAD

**Issue by chetananand** [zalando/spilo#283]
Hi,
Although spilo comes with timescaledb built as part of the Docker image, timescaledb requires that the shared_preload_libraries parameter in postgresql.conf be updated with "timescaledb" extension, which is not being done currently. Updating postgresql.conf post-init is out of the question with Patroni managing the file.

Can we please add timescaledb to the list of extensions by default ? 
https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L209

Thanks.

**Comment by k1ng440** [comment]
vote for this 
https://github.com/zalando/spilo/pull/326

**Comment by ng2dev** [comment]
Yes please!!!

**Comment by Jan-M** [comment]
@CyberDem0n

**Comment by k1ng440** [comment]
Please close this since this has been had been added to master already.

**Comment by schmitch** [comment]
btw. since timescaledb is active the build with `DEMO=true` does not work anymore.
