### ISSUE TITLE
Allow wal-g work with GCS 

### ISSUE THREAD

**Issue by pitabwire** [zalando/spilo#319]
When running the 
 
- postgres operator version: postgres-operator:v1.1.0-6-gf400539 
- spilo version: spilo-11:1.5-p7

I notice that backups to GCS using wal-e are not working because there is no way to map the kubernetes secret to a volume in the spilo pods created by the operator like when using the [helm chart](https://github.com/helm/charts/tree/master/incubator/patroni). [wal-g](https://github.com/wal-g/wal-g) promises to use the credentials on the kubernetes cluster its running on if not specified when on gcs. However when wal-g is enabled in the operator by specifying the environment variables like USE_WALG_BACKUP, the error below crops up 

  `2019-03-02 16:30:50,248 INFO: no action.  i am the leader with the lock
   2019-03-02 16:30:56.153 - /scripts/postgres_backup.sh - I was called as: /scripts/postgres_backup.sh    /home/postgres/pgdata/pgroot/data 15
   2019-03-02 16:30:56.976 40 LOG Starting pgqd 3.3
   2019-03-02 16:30:56.979 40 LOG auto-detecting dbs ...
   2019-03-02 16:30:57.159 - /scripts/postgres_backup.sh - producing a new backup
   2019/03/02 16:30:57 FATAL: Did not set the following environment variables:
WALE_S3_PREFIX
   2019-03-02 16:30:57,981 INFO reaped unknown pid 29`

Following through the [code](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L359) I see there is some limited support for GCS, is there any good reason for this limiting when wal-g supports GCS already?

**Comment by CyberDem0n** [comment]
For a long time wal-g was supporting only S3 storages, therefore there are explicit restrictions in spilo about wal-g and non S3 storages.

If you like, you can work on enabling wal-g for `GS`, `SWIFT`, `AZ` and maybe even `FILE`.
