### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by pocorschi** [zalando/spilo#323]
Steps taken
git clone
cd postgres-appliance
./build.sh --build-arg COMPRESS=true --build-arg PGOLDVERSIONS=""  -t spilo-10 .
or 
./build.sh --build-arg COMPRESS=true  -t spilo-10 .

Same error. Am I missing something?

`
File to patch:
Skip this patch? [y]
Skipping patch.
2 out of 2 hunks ignored
patching file src/client.c
Hunk #2 succeeded at 259 with fuzz 1 (offset -15 lines).
Hunk #3 succeeded at 274 (offset -15 lines).
patching file src/hba.c
The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive     && set -ex     && sed -i 's/^#\s*\(deb.*universe\)$/\1/g' /etc/apt/sources.list     && apt-get update     && cd /builddeps     && BUILD_PACKAGES="devscripts build-essential fakeroot debhelper git gcc libc6-dev make libevent-dev naturaldocs python"     && if [ "$DEMO" = "true" ]; then         PGOLDVERSIONS=""         && apt-get install -y $BUILD_PACKAGES;     else         BUILD_PACKAGES="$BUILD_PACKAGES equivs pgxnclient cmake libssl-dev zlib1g-dev libprotobuf-c-dev liblwgeom-dev libproj-dev libxslt1-dev libxml2-dev libpam0g-dev libkrb5-dev libedit-dev libselinux1-dev libcurl4-openssl-dev libicu-dev libc-ares-dev python-docutils pkg-config"         && apt-get install -y $BUILD_PACKAGES libprotobuf-c1 libcurl4         && if [ "$WITH_PERL" != "true" ]; then             version=$(apt-cache show perl | sed -n 's/^Version: //p' | sort -rV | head -n 1)             && echo "Section: misc\nPriority: optional\nStandards-Version: 3.9.8\nPackage: perl\nSection:perl\nMulti-Arch: allowed\nReplaces: perl-base\nVersion: $version\nDescription: perl" > perl             && equivs-build perl;         fi         && for p in python3-keyring python3-docutils ieee-data; do             version=$(apt-cache show $p | sed -n 's/^Version: //p' | sort -rV | head -n 1)             && echo "Section: misc\nPriority: optional\nStandards-Version: 3.9.8\nPackage: $p\nVersion: $version\nDescription: $p" > $p             && equivs-build $p;         done         && dpkg -i *.deb || apt-get -y -f install         && git clone -b $PAM_OAUTH2 --recurse-submodules https://github.com/CyberDem0n/pam-oauth2.git         && make -C pam-oauth2 install         && curl -sL https://github.com/debezium/postgres-decoderbufs/archive/$DECODERBUFS_COMMIT.tar.gz | tar xz         && curl -sL https://github.com/pgcentral/plprofiler/archive/$PLPROFILER_COMMIT.tar.gz | tar xz         && git clone -b $PLPGSQL_CHECK https://github.com/okbob/plpgsql_check.git         && git clone -b $TIMESCALEDB https://github.com/timescale/timescaledb.git         && git clone git://www.sigaev.ru/plantuner.git;     fi     && curl -sL https://github.com/CyberDem0n/bg_mon/archive/$BG_MON_COMMIT.tar.gz | tar xz     && git clone -b $SET_USER https://github.com/pgaudit/set_user.git     && apt-get install -y libevent-2.1 libevent-pthreads-2.1 python3.6 python3-psycopg2     && for version in ${PGOLDVERSIONS} ${PGVERSION}; do             sed -i "s/ main.*$/ main $version/g" /etc/apt/sources.list.d/pgdg.list             && apt-get update             && if [ "$DEMO" != "true" ]; then                 EXTRAS="postgresql-pltcl-${version}                         postgresql-${version}-hypopg                         postgresql-${version}-pgq3                         postgresql-${version}-pldebugger                         postgresql-${version}-pllua                         postgresql-${version}-plproxy                         postgresql-${version}-repack"                 && if [ $version != "11" ] && [ $version != "9.3" ] ; then                     EXTRAS="$EXTRAS postgresql-${version}-amcheck";                 fi                 && if [ "$WITH_PERL" = "true" ]; then                     EXTRAS="$EXTRAS postgresql-plperl-${version}";                 fi                 && if [ $version != "9.3" ]; then                     EXTRAS="$EXTRAS                             postgresql-${version}-partman                             postgresql-${version}-pglogical                             postgresql-${version}-postgis-${POSTGIS_VERSION}                             postgresql-${version}-postgis-${POSTGIS_VERSION}-scripts                             postgresql-${version}-wal2json"                     && if [ $version != "9.4" ]; then                         EXTRAS="$EXTRAS postgresql-${version}-pgl-ddl-deploy";                     fi;                 fi;             fi             && if [ $version != "9.3" ]; then                 EXTRAS="$EXTRAS postgresql-${version}-pg-stat-kcache"                 && if [ $version != "9.4" ]; then                     EXTRAS="$EXTRAS postgresql-${version}-cron";                 fi;             fi             && apt-get install --allow-downgrades -y postgresql-contrib-${version}                         postgresql-plpython3-${version} libpq5=$version* $EXTRAS                         libpq-dev=$version* postgresql-server-dev-${version}             && if [ "$DEMO" != "true" ]; then                 if [ "$version" != "11" ]; then                     for extension in quantile trimmed_aggregates; do                         pgxn install $extension                         && strip /usr/lib/postgresql/$version/lib/$extension.so;                     done;                 fi                 && if [ "$version" = "9.6" ] || [ "$version" = "10" ] || [ "$version" = "11" ] ; then                     cd timescaledb                     && rm -fr build                     && ./bootstrap -DAPACHE_ONLY=1                     && make -C build install                     && strip /usr/lib/postgresql/$version/lib/timescaledb*.so                     && cd ..;                 fi                 && if [ "$version" = "9.3" ] || [ "$version" = "9.4" ]; then                     REWIND_VER=REL$(echo $version | sed 's/\./_/')_STABLE                     && apt-get source postgresql-${version}                     && curl -sL https://github.com/vmware/pg_rewind/archive/${REWIND_VER}.tar.gz | tar xz                     && make -C pg_rewind-${REWIND_VER} USE_PGXS=1 top_srcdir=../$(ls -d postgresql-${version}-*) install-strip                     && rm -fr pg_rewind-${REWIND_VER} postgresql-${version}*;                 fi                 && EXTRA_EXTENSIONS="plprofiler-$PLPROFILER_COMMIT plantuner"                 && if [ "$version" != "9.3" ]; then                     EXTRA_EXTENSIONS="$EXTRA_EXTENSIONS plpgsql_check postgres-decoderbufs-$DECODERBUFS_COMMIT";                 fi;             else                 EXTRA_EXTENSIONS="";             fi             && for n in bg_mon-${BG_MON_COMMIT} set_user $EXTRA_EXTENSIONS; do                 make -C $n USE_PGXS=1 clean install-strip;             done             && apt-get purge -y libpq-dev=$version*;     done     && apt-get install -y skytools3-ticker pspg     && if [ "$DEMO" != "true" ]; then         apt-get source pgbouncer         && cd $(ls -d pgbouncer-*)         && curl -sL https://github.com/pgbouncer/pgbouncer/pull/127.diff | patch -p1         && curl -sL https://github.com/pgbouncer/pgbouncer/pull/326.diff | patch -p1         && sed -i 's/\(MAX_PASSWORD\t\).*/\11024/' include/bouncer.h         && sed -i 's/\(SEND_wrap(\)512\(, pktbuf_write_PasswordMessage, res, sk, psw)\)/\11024\2/' include/pktbuf.h         && debuild -b -uc -us         && cd ..         && dpkg -i pgbouncer_*.deb;     fi     && apt-get install -y postgresql-server-dev-all postgresql-server-dev-9.3     && for pkg in pgextwlist; do         apt-get source postgresql-10-${pkg}         && cd $(ls -d *${pkg%?}*-*)         && if [ "$pkg" = "pgextwlist" ]; then             perl -ne 'print unless /PG_TRY/ .. /PG_CATCH/' pgextwlist.c > pgextwlist.c.f             && egrep -v '(PG_END_TRY|EmitWarningsOnPlaceholders)' pgextwlist.c.f > pgextwlist.c;         fi         && rm -f debian/pgversions         && for version in ${PGOLDVERSIONS} ${PGVERSION}; do             echo ${version} >> debian/pgversions;         done         && pg_buildext updatecontrol         && debuild -b -uc -us         && cd ..         && for version in ${PGOLDVERSIONS} ${PGVERSION}; do             for deb in postgresql-${version}-${pkg}_*.deb; do                 if [ -f $deb ]; then dpkg -i $deb; fi;             done;         done;     done     && apt-get purge -y ${BUILD_PACKAGES} postgresql-server-dev-* libmagic1 bsdmainutils     && apt-get autoremove -y     && apt-get clean     && dpkg -l | grep '^rc' | awk '{print $2}' | xargs apt-get purge -y     && if [ "$DEMO" != "true" ]; then         cd /usr/lib/postgresql/$PGVERSION/bin         && for u in clusterdb pg_archivecleanup pg_basebackup pg_isready pg_test_fsync pg_test_timing pgbench psql reindexdb vacuumdb vacuumlo *.py; do             for v in /usr/lib/postgresql/*; do                 if [ "$v" != "/usr/lib/postgresql/$PGVERSION" ] && [ -f "$v/bin/$u" ]; then                     rm $v/bin/$u                     && ln -s /usr/lib/postgresql/$PGVERSION/bin/$u $v/bin/$u;                 fi;             done;         done         && cd /usr/share/postgresql/$PGVERSION/contrib/postgis-$POSTGIS_VERSION         && for f in *.sql *.pl; do             for v in /usr/share/postgresql/*; do                 if [ "$v" != "/usr/share/postgresql/$PGVERSION" ] && diff $v/contrib/postgis-$POSTGIS_VERSION/$f $f > /dev/null; then                     rm $v/contrib/postgis-$POSTGIS_VERSION/$f                     && ln -s /usr/share/postgresql/$PGVERSION/contrib/postgis-$POSTGIS_VERSION/$f $v/contrib/postgis-$POSTGIS_VERSION/$f;                 fi;             done;         done         && if [ -d /usr/share/postgresql/9.5/contrib/postgis-$POSTGIS_VERSION ]; then             cd /usr/share/postgresql/9.5/contrib/postgis-$POSTGIS_VERSION             && for f in *.sql *.pl; do                 if [ -L $f ]; then continue; fi                 && for v in $PGOLDVERSIONS; do                     if [ $v != 9.5 ] && [ -f /usr/share/postgresql/$v/contrib/postgis-$POSTGIS_VERSION/$f ]                             && [ ! -L /usr/share/postgresql/$v/contrib/postgis-$POSTGIS_VERSION/$f ]                             && diff /usr/share/postgresql/$v/contrib/postgis-$POSTGIS_VERSION/$f $f > /dev/null; then                         rm /usr/share/postgresql/$v/contrib/postgis-$POSTGIS_VERSION/$f                         && ln -s /usr/share/postgresql/9.5/contrib/postgis-$POSTGIS_VERSION/$f                                 /usr/share/postgresql/$v/contrib/postgis-$POSTGIS_VERSION/$f;                     fi;                 done;             done;         fi         && cd /usr/share/postgresql/$PGVERSION/extension         && for orig in $(ls -1 *.sql | grep -v -- '--'); do             for f in ${orig%.sql}--*.sql; do                 if diff $orig $f > /dev/null; then                     rm $f                     && ln -s $orig $f;                 fi;             done;         done         && for e in pgq plproxy address_standardizer address_standardizer_data_us; do             orig=$(ls -1 $e--*--*.sql 2> /dev/null | head -n1)             && if [ "x$orig" != "x" ]; then                 for f in $e--*--*.sql; do                     if [ "$f" != "$orig" ] && diff $f $orig > /dev/null; then                         rm $f                         && ln -s $orig $f;                     fi;                 done;             fi;         done         && for f in *.sql *.control; do             for v in /usr/share/postgresql/*; do                 if [ "$v" != "/usr/share/postgresql/$PGVERSION" ]                         && [ -f $v/extension/$f ]                         && [ ! -L $v/extension/$f ]                         && diff $v/extension/$f $f > /dev/null; then                     rm $v/extension/$f                     && ln -s /usr/share/postgresql/$PGVERSION/extension/$f $v/extension/$f;                 fi;             done;         done         && if [ -d /usr/share/postgresql/9.5/extension ]; then             cd /usr/share/postgresql/9.5/extension             && for f in *.sql *.control; do                 if [ -L $f ]; then continue; fi                 && for v in $PGOLDVERSIONS; do                     if [ $v != 9.5 ] && [ -f /usr/share/postgresql/$v/extension/$f ]                             && [ ! -L /usr/share/postgresql/$v/extension/$f ]                             && diff /usr/share/postgresql/$v/extension/$f $f > /dev/null; then                         rm /usr/share/postgresql/$v/extension/$f                         && ln -s /usr/share/postgresql/9.5/extension/$f /usr/share/postgresql/$v/extension/$f;                    fi;                 done;             done;         fi         && cd /usr/share/postgresql/$PGVERSION/contrib         && for f in *.sql *.html; do             for v in /usr/share/postgresql/*; do                 if [ "$v" != "/usr/share/postgresql/$PGVERSION" ] && diff $v/contrib/$f $f > /dev/null; then                     rm $v/contrib/$f                     && ln -s /usr/share/postgresql/$PGVERSION/contrib/$f $v/contrib/$f;                 fi;             done;         done;     fi     && find /var/log -type f -exec truncate --size 0 {} \;     && rm -rf /var/lib/apt/lists/*             /var/cache/debconf/*             /builddeps             /usr/share/doc             /usr/share/man             /usr/share/info             /usr/share/locale/??             /usr/share/locale/??_??             /usr/share/postgresql/*/man             /etc/pgbouncer/*             /usr/lib/postgresql/*/bin/createdb             /usr/lib/postgresql/*/bin/createlang             /usr/lib/postgresql/*/bin/createuser             /usr/lib/postgresql/*/bin/dropdb             /usr/lib/postgresql/*/bin/droplang             /usr/lib/postgresql/*/bin/dropuser             /usr/lib/postgresql/*/bin/pg_recvlogical             /usr/lib/postgresql/*/bin/pg_standby             /usr/lib/postgresql/*/bin/pltcl_*' returned a non-zero code: 1
'docker build --build-arg COMPRESS=true --build-arg PGOLDVERSIONS= -t spilo-10-build . -f Dockerfile.build' failed with exitcode 1`

**Comment by CyberDem0n** [comment]
That's unfortunate.
If you comment https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L207 it should help.
I'll prepare some fixes on the next week.

**Comment by pocorschi** [comment]
@CyberDem0n 
I think it's actually the following line, patching 326.diff
the source is missing config.md and that's why it fails. I prepared a modified diff [https://gist.githubusercontent.com/pocorschi/2b696da78636278cf680498bc514f4f1/raw/130a3389247bffc56136c2ea7de2cfe9b32a27e3/pgbouncer_326-fix.diff](url) that ignores it. I'd be happy to submit a PR 
I just don't know where would be best to store that diff

**Comment by CyberDem0n** [comment]
I see...
The following snippet will fix the build.
```bash
curl -sL https://github.com/pgbouncer/pgbouncer/pull/326.diff \
    | sed -n '/^diff --git a\/src\/client.c b\/src\/client.c/,$ p' | patch -p1
```
