### ISSUE TITLE
Allow S3-only replication

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/spilo#34]
This is more a discussion, than a new feature. The goal is to run the system with replicas on AWS and master in a legacy datacenter using S3 as the only medium to ship changes.

Right now, we can achieve this by creating the master member and leader keys manually without the TTL, pointing them somewhere. The replicas won't be able to connect to the master, but they will be able to initialize itself from the base backup on S3, as well as to ship WAL segments from there.

The problem is to find out how to ship WALs from the legacy datacenter to S3. We probably don't want to do it from the master, because the connection disruption from the master to AWS would risk the master running out of WAL disk space. We might use pg_receivexlog to collect those segments elsewhere and another process, using the inotify subsystem, to call WAL-E once the new segment is written by pg_receivexlog. As a side note, it would be great if pg_receivexlog could call an external command for each WAL it writes.

**Comment by LappleApple** [comment]
Hi @alexeyklyukin @CyberDem0n, do you still plan on doing this? The issue's from Dec 2015. 

WDYT about labellng "Help Wanted"?

**Comment by CyberDem0n** [comment]
It's already implemented and working like a charm
