### ISSUE TITLE
"FROM scratch" in Dockerfile causes issues for Clair

### ISSUE THREAD

**Issue by Bryji** [zalando/spilo#357]
It is a requirement in our organization to use Clair scanner on any container images being deployed to production to detect any security vulnerabilities.

It seems like the "FROM scratch" line in the multistage build causes problems for Clair, it is unable to detect the operating system type and how to scan the image:
https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L467

Removing lines 467-468 in a local branch resolved this issue for us. 

The Clair logs have messages like:
`scanResults is [nexus:[policyAlerts:[[trigger:[policyId:e2add121908a4cd08b66c0feedae47a5, policyName:Component-Unknown, threatLevel:0, componentFacts:[[componentIdentifier:null, hash:6c959be019d41fd45592, constraintFacts:[[constraintId:fbd2cee4853441f4af1cc85a8aed2fbe, constraintName:Unknown 3rd party component, operatorName:AND, conditionFacts:[[conditionTypeId:MatchState, summary:Match State is unknown, reason:Match State was unknown], `

**Comment by CyberDem0n** [comment]
Unless compression is used explicitly it s not an issue anymore
