### ISSUE TITLE
Setup wal-e/wal-g backups with minio

### ISSUE THREAD

**Issue by thepotatocannon** [zalando/spilo#359]
Hi, how can one set up wal-e/wal-g backups with minio? No matter what I try, something always goes wrong. Is it even possible?

**Comment by thepotatocannon** [comment]
Okay, update: I managed to push backups with wal-g to s3, now I need to perform PITR.

**Comment by pierreozoux** [comment]
Could you elaborate a bit please? Thanks.
I'm trying to understand the backup/recovery procedure for the Postgres operator, but the doc is not there yet ;)

**Comment by thepotatocannon** [comment]
I mainly followed this issue:
https://github.com/zalando/postgres-operator/issues/632
The idea is to use a configmap with spilo envs in order to set this up.

**Comment by vitobotta** [comment]
Hi @thepotatocannon, would you mind sharing your config? I followed that gist but I always get "NoSuchBucket". Thanks!

**Comment by thepotatocannon** [comment]
As far as I can see, you already managed to solve the problem in the issue I linked before. For the record, you can specify your bucket name in operator values.yaml:
```
  # S3 bucket to use for shipping WAL segments with WAL-E
  # wal_s3_bucket: ""
```

**Comment by vitobotta** [comment]
@thepotatocannon yep I got everything working I think :)

**Comment by endorfin** [comment]
has anyone a sample configuration for minio? Thanks!
