### ISSUE TITLE
Add option to allow non-ssl connections

### ISSUE THREAD

**Issue by alice-sawatzky** [zalando/spilo#367]
some apps (such as Geoserver) don't support connecting to the database over SSL. it would be really nice if we could disable this requirement with an environment variable

**Comment by sergeyshaykhullin** [comment]
@alice-sawatzky @CyberDem0n Can you please provide example how to use `ALLOW_NOSSL`?

**Comment by CyberDem0n** [comment]
```
docker run -e ALLOW_NOSSL=true .... spilo
```
