### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by OlleLarsson** [zalando/spilo#376]
So, I am failing to build the docker image from the master branch. Following is the the simple steps to reproduce the problem along with the resulting error message.

**Steps to reproduce**

```
git clone https://github.com/zalando/spilo.git
cd spilo/postgres-appliance
./build.sh --build-arg COMPRESS=true --tag my_tag .
```

**Error message**

```
+ apt-get source pgbouncer
Reading package lists...
NOTICE: 'pgbouncer' packaging is maintained in the 'Git' version control system at:
https://salsa.debian.org/postgresql/pgbouncer.git
Please use:
git clone https://salsa.debian.org/postgresql/pgbouncer.git
to retrieve the latest (possibly unreleased) updates to the package.
Need to get 579 kB of source archives.
Get:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main pgbouncer 1.12.0-1.pgdg18.04+1 (dsc) [1400 B]
Get:2 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main pgbouncer 1.12.0-1.pgdg18.04+1 (tar) [567 kB]
Get:3 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main pgbouncer 1.12.0-1.pgdg18.04+1 (diff) [10.1 kB]
dpkg-source: info: extracting pgbouncer in pgbouncer-1.12.0
dpkg-source: info: unpacking pgbouncer_1.12.0.orig.tar.gz
dpkg-source: info: unpacking pgbouncer_1.12.0-1.pgdg18.04+1.debian.tar.xz
dpkg-source: info: applying debian-config
dpkg-source: info: applying python3
dpkg-source: info: applying no-sudo
W: Download is performed unsandboxed as root as file 'pgbouncer_1.12.0-1.pgdg18.04+1.dsc' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
Fetched 579 kB in 1s (433 kB/s)
+ ls -d pgbouncer-1.12.0
+ cd pgbouncer-1.12.0
+ + sed -n /^diff --git a\/src\/client.c b\/src\/client.c/,$ p
patch -p1
+ curl -sL https://github.com/pgbouncer/pgbouncer/pull/326.diff
patching file src/client.c
Hunk #1 FAILED at 246.
Hunk #2 succeeded at 288 (offset 2 lines).
Hunk #3 succeeded at 303 with fuzz 2 (offset 2 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/client.c.rej
patching file src/hba.c
The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive     
    ... removed for briefness! ...     
&& find /var/log -type f -exec truncate --size 0 {} \;' returned a non-zero code: 1
```

Am I missing something?

**Comment by krorvik** [comment]
Just attempted a build off master, and you're not missing anything. It is failing due to a patch that fails to apply to pgbouncer. 

pgbouncer was added in the last commit, suggest you try building off commit 532543cbb3e3d52a1fa1ff1ca883682ac7ca906d for now.

**Comment by CyberDem0n** [comment]
Building from a different commit won't work either. I'll fix it tomorrow.

**Comment by krorvik** [comment]
Some build errors also appeared when testing without the patch throwing the first error:

dpkg-buildpackage -rfakeroot -us -uc -ui -b
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package pgbouncer
dpkg-buildpackage: info: source version 1.12.0-1.pgdg18.04+1
dpkg-buildpackage: info: source distribution bionic-pgdg
dpkg-buildpackage: info: source changed by PostgreSQL on Debian and Ubuntu <pgsql-pkg-debian@lists.postgresql.org>
 dpkg-source --before-build pgbouncer-1.12.0
dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: using options from pgbouncer-1.12.0/debian/source/options: --extend-diff-ignore=lib/usual/config.h
dpkg-checkbuilddeps: error: Unmet build dependencies: libpq-dev postgresql
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -b failed
 dpkg-buildpackage -rfakeroot -us -uc -ui -b
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package pgbouncer
dpkg-buildpackage: info: source version 1.12.0-1.pgdg18.04+1
dpkg-buildpackage: info: source distribution bionic-pgdg
dpkg-buildpackage: info: source changed by PostgreSQL on Debian and Ubuntu <pgsql-pkg-debian@lists.postgresql.org>
 dpkg-source --before-build pgbouncer-1.12.0
dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: using options from pgbouncer-1.12.0/debian/source/options: --extend-diff-ignore=lib/usual/config.h
dpkg-checkbuilddeps: error: Unmet build dependencies: libpq-dev postgresql
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -b failed

**Comment by CyberDem0n** [comment]
If you like please try https://github.com/zalando/spilo/tree/feature/pg12, there it's already fixed.

**Comment by OlleLarsson** [comment]
I tried building from the `feature/pg12` branch and I got the following error where it cannot find version 11 of libpq-dev:

```
+ apt-get purge -y devscripts build-essential fakeroot debhelper git gcc libc6-dev make cmake libevent-dev libssl-dev libkrb5-dev equivs pgxnclient zlib1g-dev libprotobuf-c-dev liblwgeom-
dev libproj-dev libxslt1-dev libxml2-dev libpam0g-dev libedit-dev libselinux1-dev libcurl4-openssl-dev libicu-dev python libc-ares-dev pandoc pkg-config postgresql-server-dev-* libpq-dev=
11* libmagic1 bsdmainutils                                                                                                                                                                 
Reading package lists...                                                                                                                                                                   
Building dependency tree...                                                                                                                                                                
Reading state information...                                                                                                                                                               
E: Version '11*' for 'libpq-dev' was not found
```

Build command executed: `./build.sh --build-arg COMPRESS=true --build-arg PGVERSION="11" --build-arg PGOLDVERSIONS="10" --tag my_tag .`

**Comment by aditya1808** [comment]
@OlleLarsson what do you mean right arguments? isnt it our choice to add which ever version we like?
