### ISSUE TITLE
Integration of docker registry into Harbor

### ISSUE THREAD

**Issue by sthroner** [zalando/spilo#387]
Hallo,

At the moment we have some issues with the integration of the Zalando Registry (https://registry.opensource.zalan.do). 
The default implementation of the docker-registry in harbor uses a HEAD Ping request for the connection check. Since the Zalando Registry uses a GET Request the integration doesn't work at the moment. 
Can some one please be so kind to tell me which registry is used at Zalando?

**Comment by CyberDem0n** [comment]
Looks like you already found the [pierone](https://github.com/zalando-stups/pierone).

**Comment by sthroner** [comment]
Yes, found it already. I close the issue. https://github.com/zalando-stups/pierone/issues/161 explains our problem pretty well.

Thanks for the work 👍
