### ISSUE TITLE
Unable to build without Postgres 11 in PGOLDVERSIONS

### ISSUE THREAD

**Issue by gertvdijk** [zalando/spilo#413]
Building master @ 84668553b9cda6ba9da199ff3b3fe9fd89cf5aec with

    $ ./build.sh [...] --build-arg PGOLDVERSIONS="" [...]

(Or anything that has no 11 in there.) Fails with:

```
+ PGVERSION=11
+ cd /usr/share/postgresql/11/contrib/postgis-3.0
/bin/sh: 1: cd: can't cd to /usr/share/postgresql/11/contrib/postgis-3.0
```

I believe that

https://github.com/zalando/spilo/blob/84668553b9cda6ba9da199ff3b3fe9fd89cf5aec/postgres-appliance/Dockerfile#L282

<strike>simply assumes that 11 is always included</strike> overrides the build-arg.

The context is that I'm trying to build an image that does not include all ancient versions of Postgres in an attempt to slim it down in size. I just want and need version 12.

I believe there's a bigger issue in those lines, because from that line on it just overrides the Docker build argument PGVERSION to 11, so the default of 12 is no longer 12 from that point. It's not obvious for me what is the solution, so I didn't create a PR (yet).

**Comment by CyberDem0n** [comment]
The issue is that timescaledb is still not available for PG12, but we want to symlink all sql files it installs on different versions in order to make the image size a bit smaller.

**Comment by DaniDD** [comment]
If I set PGVERSION to 10 and PGOLDVERSIONS="" then I become an error.
I think it need a check bevor you set the PGVERSION  to 11

**Comment by aditya1808** [comment]
@gertvdijk does it work if we give PGVERSION and PGOLDVERSIONS  both as 11 ?? 
could you confirm this plz

**Comment by gertvdijk** [comment]
> @gertvdijk does it work if we give PGVERSION and PGOLDVERSIONS both as 11 ??
> could you confirm this plz

Sorry, just noticing this now. Anyway, a PR with a fix is merged in the meantime. Should work. :)
