### ISSUE TITLE
TimeScaleDB is not working with the latest version of Spilo

### ISSUE THREAD

**Issue by rushabh-harness** [zalando/spilo#417]
Hi, I built the local docker image of Spilo as given in the instructions 

./build.sh  --build-arg COMPRESS=true --tag <TAG_NAME>

I was successfully able to build the Spilo image, however this is running PGVERSION v12. 

When I tried running the command `CREATE EXTENSION IF NOT EXISTS TIMESCALEDB CASCADE` , it failed because the extension is not available for PGVERSION v12 

Then I tried building the image using PGVERSION="11" using the following command: 

`./build.sh --build-arg PGVERSION="11" --build-arg COMPRESS=true --tag rush00121/spilo:pg_11 .`

The docker build failed midway with the following error : 

`ln: failed to create symbolic link '/usr/lib/postgresql/11/lib/postgis-2.5.so': File exists`

Now I am not sure how can I get an image with Spilo with PGVERSION11 and TimeScaleDB which works. 

I tried using this image `registry.opensource.zalan.do/acid/spilo-11:1.6-p1`, but was running into issues. 

Is there someway I can get a reliable image of Spilo with PGVERSION11 and TimeScaleDB that works. 

Thanks

**Comment by rushabh-harness** [comment]
Update: 

I got this image working but the ETCD parameter to the container is different 

docker run -it -e PATRONI_ETCD_URL="http://192.168.4.9:2379" -e SCOPE="pgCluster" --network=host --name=spilo registry.opensource.zalan.do/acid/spilo-11:1.5-p9

**Comment by CyberDem0n** [comment]
1. timescaledb doesn't support PG12 yet.
2. By default the image will contain all postgres versions starting from 9.3 to 12.
3. You can choose the version by providing `PGVERSION` environment variable when starting the image.

**Comment by Thorsten-Totemic** [comment]
Timescale just released v1.7.0 with PG12 support. Are there any plans to integrate this into Spilo?
https://github.com/timescale/timescaledb/releases/tag/1.7.0
