### ISSUE TITLE
build.sh

### ISSUE THREAD

**Issue by DwaneHall** [zalando/spilo#427]
Hey guys there does not seem to be a "build.sh" file located in the root directory of postgres-appliance folder.  The README page for building the docker image recommends:

To build the Docker Image

` $ cd postgres-appliance
$ ./build.sh --build-arg COMPRESS=true --tag $YOUR_TAG . `

Without locating this file I tried building the image using the Dockerfile directly:

`docker image build --tab spilo-postgres:test .`

But it seems to be missing some discrepancies.  Am I missing something obvious when building this image?  Any advice would be appreciated.

`E: Unable to locate package curl
E: Package 'ca-certificates' has no installation candidate
E: Package 'less' has no installation candidate
E: Package 'locales' has no installation candidate
E: Unable to locate package jq
E: Unable to locate package vim-tiny
E: Package 'gnupg1' has no installation candidate
E: Unable to locate package cron
E: Unable to locate package runit
E: Unable to locate package dumb-init
E: Unable to locate package libcap2-bin
The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive   
.......
 returned a non-zero code: 100.`  

Thanks

**Comment by CyberDem0n** [comment]
Just `docker build` should work without any problems.
The errors you see are unrelated to the removal of build.sh.

Last, but not least, we should update README and remove reference to build.sh and maybe also remove `--build-arg COMPRESS=true`, because we don't "compress" by default anymore.

**Comment by DwaneHall** [comment]
Thanks guys much appreciated. I'll have a play and see if I can figure out why the build from the Docker file directly failed.

**Comment by vitalca** [comment]
Hi,

I would like to kindly remind you to update the README. I was about to raise the same ticket.
Thanks!

**Comment by CyberDem0n** [comment]
@vitalca feel free to open a PR
