### ISSUE TITLE
Cannot run in Kubernetes with restricted PSP

### ISSUE THREAD

**Issue by steven166** [zalando/spilo#428]
Hi,
I'm unable to use the postgres-operator with Spilo in combination with the restricted PodSecurityPolicy: https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml. 

It seems that the Spilo Pods are started as the Root user and it requires some additional Linux capabilities to change ownership of files, which in my opinion should be done on build time of the Docker image. 

Therefor my question/suggestion: Can the Docker image be changed so that it runs as non-root by default without the need of changing permissions or ownerships of files. So that is can run even in Kubernetes clusters with restricted security policy's.

**Comment by CyberDem0n** [comment]
> It seems that the Spilo Pods are started as the Root user

Yes, this true, but in fact this is more like a fake root, it is limited by capabilities

> it requires some additional Linux capabilities to change ownership of files, which in my opinion should be done on build time of the Docker image.

On boot time it could try changing ownership and permissions of PGDATA which is located on the external volume. How are you going to do it on image build?

**Comment by djcass44** [comment]
FYI this should be solved by #555 

I'm successfully running Spilo 13 2.0-p5+ on OpenShift 4 using the default `restricted` SCC (i.e. no root, random UID). I have also tested this on non-OpenShift Kubernetes (Kubeadm, Minikube) by forcing the UID to a random number.
