### ISSUE TITLE
Cluster pods are running but postgre operator not able to locate them

### ISSUE THREAD

**Issue by aditya1808** [zalando/spilo#432]
I downloaded I downloaded the whole zalando/spilo:master ( **latest** - cloned the repo today) built an image and tried deploying using postgre-operator
Pods and STS are up and running but looking at the logs, seems like postgre-operator  is not able to connect to the pods..
And in pod logs, it shows Illegal Option right after generating ssl certificate

![pods_logs](https://user-images.githubusercontent.com/6763803/81067332-2a409600-8efc-11ea-90a0-260208e46bb1.png)

![operator_logs](https://user-images.githubusercontent.com/6763803/81067420-42b0b080-8efc-11ea-99d4-a140aff27137.png)

The same setup worked when i used an image built from toroNZ:master (around March 3). But with latest image its giving this error

And im not able to see any service like acid-test-cluster-config..I can only see **acid-test-cluster** and **acid-test-cluster-repl** running in my cluster.

Am i missing any config changes?

**Comment by CyberDem0n** [comment]
I can't tell what exactly you did wrong, but the https://github.com/zalando/spilo/releases/tag/1.6-p3 is built from the master branch a few days ago and it perfectly works.

**Comment by aditya1808** [comment]
thanks for quick response.
After using **tag/1.6-p3** its working fine.
