### ISSUE TITLE
issue when cloning https://github.com/CyberDem0n/pam-oauth2.git 

### ISSUE THREAD

**Issue by aditya1808** [zalando/spilo#433]
Hi, im trying to build latest version 1.6-p3 in my company network using proxy.
ENV http_proxy=""
ENV https_proxy=""

I have provided proxy like mentioned above, in the Docker file.
But when building its failing when its trying to pull pam-oauth2 ,one of its submodules actually.

![image](https://user-images.githubusercontent.com/6763803/81187179-52e68f80-8fd1-11ea-8265-95cf9c450ef0.png)

i believe this submodule is using git:// instead of https://

Could you let me know how to fix this.

**Comment by CyberDem0n** [comment]
If you change https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L77 to PAM_OAUTH2=v1.0.1 it should help

**Comment by aditya1808** [comment]
thanks, that helped. I will close the ticket but i just want to know, is there any reason why its not implemented in spilo? ( **to use v1.0.1**)??
