### ISSUE TITLE
make image tag consistent with gh releases

### ISSUE THREAD

**Issue by k0da** [zalando/spilo#434]
I just found 1.6-p3 image isn't yet available, last available one is 1.6-p1.

We have an automation in place for mirroring images based on GH releases. Currently it looks like image build process isn't coupled with GH release.
```
docker pull registry.opensource.zalan.do/acid/spilo-11:1.6-p3
Error response from daemon: manifest for registry.opensource.zalan.do/acid/spilo-11:1.6-p3 not found
```

**Comment by CyberDem0n** [comment]
That's because there is no new spilo-11 anymore, but spilo-12.
The latest is `registry.opensource.zalan.do/acid/spilo-12:1.6-p3`

**Comment by k0da** [comment]
@CyberDem0n yeah, just figured out, is that -12 set manually? or is this a branch?

**Comment by CyberDem0n** [comment]
Image name and tag are generated automatically: https://github.com/zalando/spilo/blob/master/delivery.yaml

**Comment by k0da** [comment]
Thanks
