### ISSUE TITLE
setting password for superuser

### ISSUE THREAD

**Issue by aditya1808** [zalando/spilo#442]
Hi, how do we set passowrd for super user during installation of cluster using pg-operator?
i couldnt find much. I could only get below info which needs to be set in manifest file
  users:
    # database owner
    zalando:
    - superuser
    - createdb

but it doesnt have any field for password for that user. Please help.

**Comment by CyberDem0n** [comment]
Please don't cross-post: https://github.com/zalando/postgres-operator/issues/1000

**Comment by aditya1808** [comment]
@CyberDem0n Could you please provide the information on how to provide a password in manifest file for manifest roles.
