### ISSUE TITLE
authentication md5 for local connections as default config  during installtion

### ISSUE THREAD

**Issue by aditya1808** [zalando/spilo#445]
Hi,
When i enter psql -U postgres, its not asking for a password. Local connections are set to trust in hba_file.

![image](https://user-images.githubusercontent.com/6763803/83949098-8e2de580-a83f-11ea-953c-a0dbeb793ece.png)

is there a way to set it to md5 during installation? Sorry, i couldnt find any way to do it. Please help!

**Comment by CyberDem0n** [comment]
There is not much point in protecting local connections in the docker container.
