### ISSUE TITLE
Make default DCS path more unique

### ISSUE THREAD

**Issue by a1exsh** [zalando/spilo#45]
The default DCS path `/service/{scope}` might look a bit confusing if the scope doesn't include `spilo` anywhere in it.

For example, when testing I have the habit of creating stacks while putting just an increasing number for the version, e.g. `senza create myspilo.yaml 7`.  This will end up with `/service/7` in the DCS, which might be not unique enough, especially given there is usually no authn/authz in the DCS: everyone can write anywhere.

How about using `/service/spilo/{scope}` by default instead?  Can this be configured at the moment?

**Comment by feikesteenbergen** [comment]
You can set a namespace, it defaults to '/service/'

https://github.com/zalando/patroni/blob/master/patroni/dcs.py#L169
