### ISSUE TITLE
How to add pg_prometheus extension

### ISSUE THREAD

**Issue by RyanWN4** [zalando/spilo#451]
Hey guys, I'm wondering how can I add the pg_prometheus extension into this. I've deployed the patroni cluster using incubator/patroni helm chart and it all works a charm but I need to install the pg_prometheus extension. Any pointers would be great

**Comment by CyberDem0n** [comment]
> SUNSET NOTICE

> We'll be sunsetting this project in the coming months as we focus on a new implementation with additional functionality and better support for new TimescaleDB features (such as compression). You can find the new project at https://github.com/timescale/timescale-prometheus.

> More details can be found in our design document for the new project.

> This project will continue only in maintenance mode.

After reading https://github.com/timescale/pg_prometheus I can only recommend to fork-patch-build your own image approach.

**Comment by RyanWN4** [comment]
Yeah so I've seen their trying to move people towards timescale db (Rather than using native postgres + an extension). Will give that a go though. Thanks! :)
