### ISSUE TITLE
New Release for bug fixes

### ISSUE THREAD

**Issue by connorearl** [zalando/spilo#460]
It would be great to have a new release soon so I can have the fixes applied in #447 in my cluster. 

Currently I'm stuck changing permissions manually every time the operator restarts and statefulsets, as I cannot add the chmod command to the operator manifest to run before it starts.

**Comment by stoetti** [comment]
@CyberDem0n any plans on a new release that includes the mentioned fix?

**Comment by CyberDem0n** [comment]
Done: registry.opensource.zalan.do/acid/spilo-12:1.6-p5
