### ISSUE TITLE
Dockerfile build fails: pulling non-existing branch

### ISSUE THREAD

**Issue by Legogris** [zalando/spilo#463]
The git branch referenced at https://github.com/zalando/spilo/blob/c307996bea5a734481aebaf403aee31584aa366f/postgres-appliance/Dockerfile#L423 does not exist - therefore building the current Docker image fails.

**Comment by CyberDem0n** [comment]
Yes, sorry about that. I restored the branch, now it should work.

**Comment by Legogris** [comment]
Image builds fine now, thanks!
