### ISSUE TITLE
Make etcd optional

### ISSUE THREAD

**Issue by Legogris** [zalando/spilo#468]
Current version of Docker image is starting etcd regardless of if it's used or not. When using other dcs, etcd should not be started. @CyberDem0n Would you prefer a new env var to toggle this, or should it be derived by checking for presence of `ETCD_HOST`/`ETCD_HOSTS`/`ETCD_URL`?

**Comment by CyberDem0n** [comment]
Modifying https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L899-L906 should be enough:
```python
    if provider == PROVIDER_LOCAL and not USE_KUBERNETES and\
            not any(e in placeholders for e in ('ETCD_DISCOVERY_DOMAIN', 'ETCD_HOST', 'ETCD_HOSTS', 'ETCD_URL',
                                                'ETCD_PROXY', 'ZOOKEEPER_HOSTS', 'EXHIBITOR_HOSTS', 'CONSUL_HOST')):
        write_etcd_configuration(placeholders)
```

The handling of `CONSUL_HOST` should be implemented though.

**Comment by Legogris** [comment]
Unless I'm missing something, the etcd service will still be started at container startup regardless of presence of config, no?

**Comment by CyberDem0n** [comment]
`write_etcd_configuration()` configures `runit` service.
If there is no service it will not start etcd.
