### ISSUE TITLE
Changing port from 5432 breaks unix socket connections

### ISSUE THREAD

**Issue by Legogris** [zalando/spilo#469]
When changing listening port, connection is attempted to unix socket at incorrect path.

E.g., when setting `PGPORT=1337` and `listen: *:1337`:

```
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**Comment by CyberDem0n** [comment]
Well, we never expected that someone will use a non-default port _in docker_ container. Not sure that such a use-case is deserving time spent on it.

**Comment by Legogris** [comment]
Then maybe the env var should be removed? The docs currently state it as configurable.

**Comment by CyberDem0n** [comment]
Maybe if you add `PGPORT` [here](https://github.com/zalando/spilo/blob/master/postgres-appliance/runit/patroni/run#L15) it will fix the issue, that would be an easy win.
