### ISSUE TITLE
Permission error "/run/certs/server.key":

### ISSUE THREAD

**Issue by marco-giovannini-clevertech** [zalando/spilo#479]
I am running the image registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p128 and I see this error and posgress fail to start.

FATAL:  could not load private key file "/run/certs/server.key": Permission denied

root@acid-pgop-postgres-xxxx-xxxxx-0:/home/postgres# ls -l  "/run/certs/server.key"
-rw------- 1 root root 1708 Aug 10 12:33 /run/certs/server.key

**Comment by CyberDem0n** [comment]
Without telling how you started it up I can't advise anything.
By default configure_spilo.py sets the user on the file to `postgres`.

**Comment by marco-giovannini-clevertech** [comment]
I had to delete that installation but today I was trying to replicate it without success. 
I don't get anymore this error but I get a new one :( 

2020-08-12 12:00:13,885 ERROR: Exception when saving file: /home/postgres/pgdata/pgroot/data/patroni.dynamic.json                                                                      │
│ postgres Traceback (most recent call last):                                                                                                                                                     │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 140, in save_cache                                                                                             │
│ postgres     (fd, tmpfile) = tempfile.mkstemp(prefix=self.__CACHE_FILENAME, dir=self._data_dir)                                                                                                 │
│ postgres   File "/usr/lib/python3.6/tempfile.py", line 483, in mkstemp                                                                                                                          │
│ postgres     return _mkstemp_inner(dir, prefix, suffix, flags, output_type)                                                                                                                     │
│ postgres   File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner                                                                                                                   │
│ postgres     fd = _os.open(file, flags, 0o600)                                                                                                                                                  │
│ postgres FileNotFoundError: [Errno 2] No such file or directory: '/home/postgres/pgdata/pgroot/data/patroni.dynamic.json63w4jwyo'                                                               │
│ postgres 2020-08-12 12:00:23,836 INFO: removing initialize key after failed attempt to bootstrap the cluster                                                                                    │
│ postgres 2020-08-12 12:00:23,888 ERROR: Unexpected exception                                                                                                                                    │
│ postgres Traceback (most recent call last):                                                                                                                                                     │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1385, in run_cycle                                                                                                 │
│ postgres     info = self._run_cycle()                                                                                                                                                           │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1288, in _run_cycle                                                                                                │
│ postgres     return self.post_bootstrap()                                                                                                                                                       │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1184, in post_bootstrap                                                                                            │
│ postgres     self.cancel_initialization()                                                                                                                                                       │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1179, in cancel_initialization                                                                                     │
│ postgres     raise PatroniException('Failed to bootstrap cluster')                                                                                                                              │
│ postgres patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'


Seems the path doesn't exists.

root@acid-pgop-postgres-xxxxxx-xxxx-0:/home/postgres/pgdata/pgroot# ls -l
total 8
drwx------ 19 postgres postgres 4096 Aug 12 09:50 data_2020-08-12-09-50-32
drwxr-xr-x  2 postgres postgres 4096 Aug 12 09:50 pg_log

I am deploying the Postgres cluster using the Postgres operator v1.5.0 and spilo-cdp-12:1.6-p128.

Here the manifest. 

apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  creationTimestamp: "2020-08-12T09:50:05Z"
  generation: 1
  name: acid-pgop-postgres-xxxxx-xxxx
  namespace: default
  resourceVersion: "59916928"
  selfLink: /apis/acid.zalan.do/v1/namespaces/default/postgresqls/acid-pgop-postgres-xxxxx-xxxx
  uid: b43f03f5-8490-4ad6-a033-5bfaef6aaab3
spec:
  allowedSourceRanges:
  - 127.0.0.1/32
  databases:
    test: xxxx
  dockerImage: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p128
  enableLogicalBackup: false
  enableShmVolume: true
  logicalBackupSchedule: 0 0 * * *
  numberOfInstances: 3
  patroni:
    initdb:
      data-checksums: "true"
      encoding: UTF8
      locale: en_US.UTF-8
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5
    retry_timeout: 10
    ttl: 30
  postgresql:
    parameters:
      checkpoint_timeout: 5min
      effective_cache_size: "125"
      hot_standby_feedback: "true"
      log_statement: all
      maintenance_work_mem: 6MB
      max_connections: "559"
      max_wal_size: 5GB
      shared_buffers: "62"
      work_mem: 6MB
    version: "12"
  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 250m
      memory: 250Mi
  sidecars:
  - env:
    - name: DATA_SOURCE_URI
      value: 127.0.0.1:5432/postgres?sslmode=disable
    - name: DATA_SOURCE_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: xxxxxxx.credentials
    - name: DATA_SOURCE_PASS
      valueFrom:
        secretKeyRef:
          key: password
          name: xxxxxxxx.credentials
    image: wrouesnel/postgres_exporter:v0.8.0
    name: exporter
    ports:
    - containerPort: 9187
      name: exporter
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  teamId: acid
  users:
    devs:
    - login
    xxxxxx:
    - superuser
    - createdb
  volume:
    size: 10Gi
    storageClass: ssd
status:
  PostgresClusterStatus: Creating

**Comment by CyberDem0n** [comment]
There should be one or more errors earlier, they will explain why bootstrap failed.

**Comment by marco-giovannini-clevertech** [comment]
There is just this line before that I didn't copy:
postgres 2020-08-12 12:46:59,763 INFO: Unexpected exception raised, please report it as a BUG  
                                                                                                 
Otherwise, I don't see other errors except this, it repeats over and over.

**Comment by CyberDem0n** [comment]
There should be more.

**Comment by marco-giovannini-clevertech** [comment]
You are right I there are some other errors, one is the initial error I opened this issue for :)  I wasn't just fast enough to catch it. 
It seems to show just at the starting of the pod. 
I had to delete the pod and let it recreate to be able to see it.

postgres 2020-08-12 12:59:23,116 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)                                                                          │
│ postgres 2020-08-12 12:59:23,220 - bootstrapping - INFO - Looks like your running google                                                                                                        │
│ postgres 2020-08-12 12:59:23,315 - bootstrapping - INFO - Configuring pam-oauth2                                                                                                                │
│ postgres 2020-08-12 12:59:23,316 - bootstrapping - INFO - Writing to file /etc/pam.d/postgresql                                                                                                 │
│ postgres 2020-08-12 12:59:23,316 - bootstrapping - INFO - Configuring log                                                                                                                       │
│ postgres 2020-08-12 12:59:23,316 - bootstrapping - INFO - Configuring crontab                                                                                                                   │
│ postgres 2020-08-12 12:59:23,316 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability                                                               │
│ postgres 2020-08-12 12:59:23,317 - bootstrapping - INFO - Configuring patroni                                                                                                                   │
│ postgres 2020-08-12 12:59:23,403 - bootstrapping - INFO - Writing to file /home/postgres/postgres.yml                                                                                           │
│ postgres 2020-08-12 12:59:23,404 - bootstrapping - INFO - Configuring wal-e                                                                                                                     │
│ postgres 2020-08-12 12:59:23,404 - bootstrapping - INFO - Configuring certificate                                                                                                               │
│ postgres 2020-08-12 12:59:23,404 - bootstrapping - INFO - Generating ssl certificate                                                                                                            │
│ postgres Traceback (most recent call last):                                                                                                                                                     │
│ postgres   File "/scripts/configure_spilo.py", line 1018, in <module>                                                                                                                           │
│ postgres     main()                                                                                                                                                                             │
│ postgres   File "/scripts/configure_spilo.py", line 986, in main                                                                                                                                │
│ postgres     write_certificates(placeholders, args['force'])                                                                                                                                    │
│ postgres   File "/scripts/configure_spilo.py", line 110, in write_certificates                                                                                                                  │
│ postgres     uid = pwd.getpwnam(environment['PGUSER_SUPERUSER']).pw_uid                                                                                                                         │
│ postgres KeyError: "getpwnam(): name not found: 'pg-root'"                                                                                                                                      │
│ postgres 2020-08-12 12:59:25,716 INFO: No PostgreSQL configuration items changed, nothing to reload.                                                                                            │
│ postgres 2020-08-12 12:59:25,719 INFO: Lock owner: None; I am acid-pgop-postgres-alumni-connect-0                                                                                               │
│ postgres 2020-08-12 12:59:25,904 INFO: trying to bootstrap a new cluster                                                                                                                        │
│ postgres The files belonging to this database system will be owned by user "postgres".                                                                                                          │
│ postgres This user must also own the server process.                                                                                                                                            │
│ postgres The database cluster will be initialized with locale "en_US.UTF-8".                                                                                                                    │
│ postgres The default text search configuration will be set to "english".                                                                                                                        │
│ postgres Data page checksums are enabled.                                                                                                                                                       │
│ postgres fixing permissions on existing directory /home/postgres/pgdata/pgroot/data ... ok                                                                                                      │
│ postgres creating subdirectories ... ok                                                                                                                                                         │
│ postgres selecting dynamic shared memory implementation ... posix                                                                                                                               │
│ postgres selecting default max_connections ... 100                                                                                                                                              │
│ postgres selecting default shared_buffers ... 128MB
postgres selecting default time zone ... Etc/UTC                                                                                                                                                │
│ postgres creating configuration files ... ok                                                                                                                                                    │
│ postgres running bootstrap script ... ok                                                                                                                                                        │
│ postgres performing post-bootstrap initialization ... ok                                                                                                                                        │
│ postgres syncing data to disk ... ok                                                                                                                                                            │
│ postgres Success. You can now start the database server using:                                                                                                                                  │
│ postgres     /usr/lib/postgresql/12/bin/pg_ctl -D /home/postgres/pgdata/pgroot/data -l logfile start                                                                                            │
│ postgres 2020-08-12 12:59:30.507 UTC [64] FATAL:  could not load private key file "/run/certs/server.key": Permission denied                                                                    │
│ postgres 2020-08-12 12:59:30.507 UTC [64] LOG:  database system is shut down                                                                                                                    │
│ postgres 2020-08-12 12:59:30,606 INFO: postmaster pid=64                                                                                                                                        │
│ postgres /var/run/postgresql:5432 - no response                                                                                                                                                 │
│ postgres 2020-08-12 12:59:30,697 INFO: removing initialize key after failed attempt to bootstrap the cluster                                                                                    │
│ postgres 2020-08-12 12:59:30,745 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2020-08-12-12-59-30                                                                         │
│ postgres 2020-08-12 12:59:30,796 ERROR: Unexpected exception                                                                                                                                    │
│ postgres Traceback (most recent call last):                                                                                                                                                     │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1385, in run_cycle                                                                                                 │
│ postgres     info = self._run_cycle()                                                                                                                                                           │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1288, in _run_cycle                                                                                                │
│ postgres     return self.post_bootstrap()                                                                                                                                                       │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1184, in post_bootstrap                                                                                            │
│ postgres     self.cancel_initialization()                                                                                                                                                       │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1179, in cancel_initialization                                                                                     │
│ postgres     raise PatroniException('Failed to bootstrap cluster')                                                                                                                              │
│ postgres patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'                                                                                                                     │
│ postgres 2020-08-12 12:59:30,798 INFO: Unexpected exception raised, please report it as a BUG                                                                                                   │
│ postgres 2020-08-12 12:59:30,799 ERROR: Exception when saving file: /home/postgres/pgdata/pgroot/data/patroni.dynamic.json                                                                      │
│ postgres Traceback (most recent call last):                                                                                                                                                     │
│ postgres   File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 140, in save_cache                                                                                             │
│ postgres     (fd, tmpfile) = tempfile.mkstemp(prefix=self.__CACHE_FILENAME, dir=self._data_dir)                                                                                                 │
│ postgres   File "/usr/lib/python3.6/tempfile.py", line 483, in mkstemp                                                                                                                          │
│ postgres     return _mkstemp_inner(dir, prefix, suffix, flags, output_type)                                                                                                                     │
│ postgres   File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner

**Comment by CyberDem0n** [comment]
> │ postgres 2020-08-12 12:59:30.507 UTC [64] FATAL: could not load private key file "/run/certs/server.key": Permission denied │

You see? This is the same error.

**Comment by marco-giovannini-clevertech** [comment]
I see it now but it behaves a bit differently.

Last time it was getting stuck at this 'Permission error',  now it throws it one time and moves on showing later another error.

**Comment by marco-giovannini-clevertech** [comment]
Just some finding meanwhile I keep digging.

In another cluster we have with version registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p16 the cetificatificate seem created in the /home/postgres/ with the following owner/permissions 

-rw-r--r-- 1 root     root     1131 Aug  6 08:25 server.crt
-rw------- 1 postgres root     1704 Aug  6 08:25 server.key

In the registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p128 we have running they get created in /run/certs with the following owner and permission

root@acid-pgop-postgres-alumni-connect-1:/run/certs# ls -l
total 8
-rw-r--r-- 1 root root 1131 Aug 12 09:50 server.crt
-rw------- 1 root root 1704 Aug 12 09:50 server.key

**Comment by marco-giovannini-clevertech** [comment]
I am moving a bit forward :) 

In the end, write_certificate function owner and permissions are assigned.

```
def write_certificates(environment, overwrite):
   .
   .   
    uid = pwd.getpwnam(environment['PGUSER_SUPERUSER']).pw_uid
    os.chmod(environment['SSL_PRIVATE_KEY_FILE'], 0o600)
    os.chown(environment['SSL_PRIVATE_KEY_FILE'], uid, -1)

```

In my case still not sure why PGUSER_SUPERUSER has value pg-root instead of postgres. 
The user pg-root doesn't exist

root@acid-pgop-postgres-xxxxx-xxxxxx-0:/home/postgres# env | grep PGUSER_SUPERUSER
PGUSER_SUPERUSER=pg-root

root@acid-pgop-postgres-xxxxx-xxxxxx-0:/home/postgres# cat /etc/passwd | grep pg-root
root@acid-pgop-postgres-xxxxx-xxxxx-0:/home/postgres#

│ postgres 2020-08-12 12:59:23,404 - bootstrapping - INFO - Generating ssl certificate │
│ postgres Traceback (most recent call last): │
│ postgres File "/scripts/configure_spilo.py", line 1018, in │
│ postgres main() │
│ postgres File "/scripts/configure_spilo.py", line 986, in main │
│ postgres write_certificates(placeholders, args['force']) │
│ postgres File "/scripts/configure_spilo.py", line 110, in write_certificates │
│ postgres uid = pwd.getpwnam(environment['PGUSER_SUPERUSER']).pw_uid │
│ postgres KeyError: "getpwnam(): name not found: 'pg-root'" │

**Comment by CyberDem0n** [comment]
I think we should simply use hardcoded `postgres` instead of `environment['PGUSER_SUPERUSER'], because Patroni/PostgreSQL are starting as `postgres` anyway.

**Comment by marco-giovannini-clevertech** [comment]
Ok, I am going to work on a PR for it. Thanks

**Comment by usernkey** [comment]
#480
