### ISSUE TITLE
Open port 9100 in the security group for ZMON to get the CloudWatch Metrics

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/spilo#48]
The ZMON Zalando monitoring tool can be deployed into each AWS account to allow cross-team monitoring and dashboards. Make sure that ZMON appliance is allowed by security groups to connect to port 9100 of monitored instances.

http://docs.stups.io/en/latest/user-guide/monitoring.html

**Comment by a1exsh** [comment]
I think 9100 is actually Prometheus agent, not a cloud watch thing, right?

**Comment by feikesteenbergen** [comment]
https://github.com/zalando-stups/senza/pull/193
