### ISSUE TITLE
Change patroni config in spilo

### ISSUE THREAD

**Issue by alizaya** [zalando/spilo#491]
Hi, I Want to change the config of Postgres and I search a lot and find out I have to change SPILO_CONFIGURATION env in spilo but it does not exist in https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst file.

is SPILO_CONFIGURATION still working?

**Comment by CyberDem0n** [comment]
> is SPILO_CONFIGURATION still working?

Yes.
