### ISSUE TITLE
Where is build.sh script?

### ISSUE THREAD

**Issue by Nizarius** [zalando/spilo#492]
Hi, guys! Looks like your Readme is not up to date.

Master doesn't have "build.sh" file in postgres-appliance folder: https://github.com/zalando/spilo/tree/master/postgres-appliance.

Moreover, I found only one "build.sh" file — in ./postgres-appliance/dependencies/build.sh. I'm not sure if it's the right script to compile as after compiling this image doesn't contain any postgresql libraries.

So how should I compile this image for my use?

**Comment by CyberDem0n** [comment]
Just use normal `docker build`, no scripts is required.
