### ISSUE TITLE
Improper building?

### ISSUE THREAD

**Issue by seenutn** [zalando/spilo#494]
Hi,
   I tried to build using the README.md and the command I used is 

cd /home/seenutn/temp/spilo/postgres-appliance/dependencies
./build.sh --build-arg COMPRESS=true --tag pat1 PGVERSION="12"

   But it has created an docker image with tag "dependencies" instead of the tag given on command line.  Also, thus created image contains nothing of the applications - no postgres, no timescale, no patroni, etc..  What am I doing wrong?

If it helps, I am attaching the log file when I ran build.
[typescript.txt](https://github.com/zalando/spilo/files/5266616/typescript.txt)

**Comment by CyberDem0n** [comment]
```bash
cd spilo/postgres-appliance
docker build -t spilo .
```
