### ISSUE TITLE
Docker Image build fails for pgbouncer

### ISSUE THREAD

**Issue by mindw00rk** [zalando/spilo#505]
pandoc -s -t man -o pgbouncer.5 pgbouncer_5.md
pandoc: pgbouncer_5.md: openFile: does not exist (No such file or directory)
Makefile:23: recipe for target 'pgbouncer.5' failed
make[2]: *** [pgbouncer.5] Error 1

**Comment by CyberDem0n** [comment]
False claim. Build from the master brunch succeeds: https://github.com/zalando/spilo/runs/1197399856
