### ISSUE TITLE
Q: E: Version '12*' for 'libpq5' was not found, "docker build ..."

### ISSUE THREAD

**Issue by Samusername** [zalando/spilo#506]
Hi! I would have a question.

3 or 4 days ago, compilation of spilo has worked in:
https://github.com/zalando/spilo/runs/1197399856
(Link is from previous ticket.)

I am not sure why following error comes from local compilation, on my laptop.

I get following kind of an error, when I try to compile spilo image with Dockerfile:
E: Version '12*' for 'libpq5' was not found
E: Version '12*' for 'libpq-dev' was not found

I downloaded source codes from:
https://github.com/zalando/spilo/releases
1.6-p5 and 1.6-p3
docker build failed.

I tried to debug something,
I e.g. ran "docker run ... ubuntu:18.04 ...", --> plain ubuntu:18.04 in docker container.
I tried to add following repo.
DISTRIB_CODENAME=$(sed -n 's/DISTRIB_CODENAME=//p' /etc/lsb-release) \
echo "deb http://apt.postgresql.org/pub/repos/apt/ ${DISTRIB_CODENAME}-pgdg main" >> /etc/apt/sources.list.d/pgdg.list

"apt update"
"apt list -a libpq5", output:
libpq5/bionic-pgdg 13.0-1 ...
libpq5/bionic-updates,bionic-security 10.14 ...
libpq5/bionic 10.3-1 ...
 
But not release 12. Nor 11. ? Should those be there, or how should it work?

Side note: There is ubuntu 20.04 on my laptop, and docker from docker.io.

**Comment by CyberDem0n** [comment]
Any single reason you don't want to use the master branch?
It was fixed in the https://github.com/zalando/spilo/commit/53a992a4cc42c505a8ece90e0af170b0dfa08891

**Comment by Samusername** [comment]
Ok. Good to know.

I learned also new things:
Packages for older postgresql releases seem to be in following location:
https://apt-archive.postgresql.org/
deb https://apt-archive.postgresql.org/pub/repos/apt DIST-pgdg-archive main
I am trying with such now also.

( I am learning new topics continuously. )
