### ISSUE TITLE
Replicas fail regularly when /etc/service dissapears

### ISSUE THREAD

**Issue by jf647** [zalando/spilo#511]
I'm running Spilo via postgres-operator.  I have a cluster of 3 pods on a GKE Kubernetes cluster.  Every 24-36 hours, one or both of the replicas fails.  If I tail the pod logs, I see this over and over again:

```
default/nadt-pgsql-2[postgres]: runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
```

And indeed, if I check the pod, /run/service (which /etc/service is linked to) is gone:

```
$ kubectl exec -i -t -n default nadt-pgsql-0 -- ls -la /etc/service
lrwxrwxrwx 1 root root 12 Apr 24  2020 /etc/service -> /run/service
$ kubectl exec -i -t -n default nadt-pgsql-0 -- ls -la /run/service
ls: cannot access '/run/service': No such file or directory
command terminated with exit code 2
```

Immediately preceeding the runsvdir errors in the log, I get a series of uncaught exceptions, which I've copied in this gist:

https://gist.github.com/jf647/b5404f6102b0917f1db43f3e76afce3e

My pods are running the registry.opensource.zalan.do/acid/spilo-12:1.6-p3 image and my postres-operator is running registry.opensource.zalan.do/acid/postgres-operator:v1.5.0.

Deleting the affected pods and allowing them to bootstrap from the master seems to clear things up, but that's toil and I'm hoping to get to the root of how the containers get into this state.  I'm not sure what other data to collect, but as it happens so often I can grab anything needed the next time it happens.

**Comment by jf647** [comment]
Should this have been opened in zalando/postgres-operator instead?  I'm having to restart containers every day (because the pod template doesn't allow a sidecar definition), and if it happens in the middle of the night (this is a personal DB providing no critical services, and thus doesn't page 24/7), all of the pods have usually failed and I have to restore from backup.

**Comment by CyberDem0n** [comment]
You need to figure out what wipes out /run directory.
There's nothing in spilo what could do that.

**Comment by jf647** [comment]
As the gist shows, this is an uncaught Python exception when configure_spilo.py is running.

It appears that the script fails to gracefully degrade if the DNS lookup for the metadata server fails:

https://github.com/zalando/spilo/blob/85da543f8a5eb64e26cb67e248e9dee22091ee09/postgres-appliance/scripts/configure_spilo.py#L313

```
Max retries exceeded with url: /computeMetadata/v1/instance/zone
```

```
Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

So it's not that something is deleting the runit dir, it's that it is never being created but runsvdir is still being started.

**Comment by CyberDem0n** [comment]
Oh, missed it. Gist isn't very readable.
I can only suggest to wrap this line with try...catch and see if it helps. Information about zone currently is not used anyway.

**Comment by alexeyklyukin** [comment]
I've stumbled upon this problem as well when running Spilo in the Google environment. If you have a sort-of-working DNS that can resolve addresses inside the K8S cluster, but outside resolutions doesn't work, the [request to metadata.google.internal](https://github.com/zalando/spilo/blob/931c26dd0261cb9e552357ba8bac04886c671423/postgres-appliance/scripts/configure_spilo.py#L379) gives a `Temporary failure in name resolution` (similar to the gist above).

I think we can anyway check that /etc/service exist before [the final line in launch.sh](https://github.com/zalando/spilo/blob/380d45377029cd8f541011b51f3ac124392e312f/postgres-appliance/launch.sh#L58), but perhaps we could also avoid using DNS with google altogether? The address is points to is `169.254.169.254` and it's unlikely google changes it in the observable future.

The alternative would be to wrap the line above from `get_instance_metadata` with exception handling and fail hard if it fails.

**Comment by CyberDem0n** [comment]
The `get_instance_metadata()` is useful only when we run Spilo directly on the instance.
I think nowadays it is very rarely the case. People mostly run Spilo on K8s, where we simply could ignore any exception.

Changing `metadata.google.internal` to `169.254.169.254` might be a good alternative. I agree, it is very unlikely that IP could be changed. My only concern about it that they might check the `Host:` header and depending on the value deliver a different result.
We could check that by comparing responses for `http://metadata.google.internal/computeMetadata/v1/instance/zone` and `http://169.254.169.254/computeMetadata/v1/instance`. Since I don't have access to GCP I can't do it myself.

**Comment by alexeyklyukin** [comment]
@CyberDem0n 
it works for me:
```
curl -H "Metadata-Flavor: Google"  http://169.254.169.254/computeMetadata/v1/instance/id
5771040814979217996
curl -H "Metadata-Flavor: Google"  http://169.254.169.254/computeMetadata/v1/instance/zone
projects/139922888928/zones/europe-west3-a
```

>The get_instance_metadata() is useful only when we run Spilo directly on the instance.
> I think nowadays it is very rarely the case. People mostly run Spilo on K8s, where we simply could ignore any exception.

AFAICT when [ logging to S3](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L665-L674) and [the S3 WALE configuration](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L720-L729) the `zone` and instance `id` are used, although that is not relevant to GCP.

We could avoid gathering those altogether for GCP when `USE_KUBERNETES` is enabled, but it seems error prone as a special case; what if someone in the future decides to make use of it. Using the IP address seems justified: by the time we try to gather the metadata we already know it works from the `get_provider()`.

**Comment by alexeyklyukin** [comment]
@jf647 can you try building the docker image from master and see if you still have the errors reported?
