### ISSUE TITLE
The case of the disappearing GCP metadata-server

### ISSUE THREAD

**Issue by haf** [zalando/spilo#527]
I was browsing the logs as the service starts, as I want to ensure it uses GCP for backups, and I saw:

```
app-analytics-db-0 postgres 2020-12-20 14:16:08,259 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
app-analytics-db-0 postgres 2020-12-20 14:16:08,264 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
app-analytics-db-0 postgres 2020-12-20 14:16:08,265 - bootstrapping - INFO - No meta-data available for this provider
app-analytics-db-0 postgres 2020-12-20 14:16:08,265 - bootstrapping - INFO - Looks like your running local
app-analytics-db-0 postgres 2020-12-20 14:16:08,299 - bootstrapping - INFO - Configuring bootstrap
```

However; 
```
$ k exec app-analytics-db-0 -c postgres -- curl -v --silent http://169.254.169.254
* Rebuilt URL to: http://169.254.169.254/
*   Trying 169.254.169.254...
* TCP_NODELAY set
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET / HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.58.0
> Accept: */*
>
computeMetadata/
< HTTP/1.1 200 OK
< content-type: application/text
< metadata-flavor: Google
< server: envoy
< date: Sun, 20 Dec 2020 14:18:23 GMT
< content-length: 17
< x-envoy-upstream-service-time: 0
<
{ [17 bytes data]
* Connection #0 to host 169.254.169.254 left intact
```

The server is there and responding. Why would Spilo say otherwise?

**Comment by CyberDem0n** [comment]
> Why would Spilo say otherwise?

It could be a race condition, when spilo starts the metadata wasn't available, but later it already is, but that should not affect backups.
Only `WALE_GS_PREFIX` and `GOOGLE_APPLICATION_CREDENTIALS` environment variables specify that GCS should be used.

**Comment by haf** [comment]
Race:
Maybe; because there's an istio sidecar proxy coming up at the same time: and iptables have ensured all outgoing connections must go through it, but the envoy proxy hasn't yet started. What does this affect and how can I solve it?

Env vars:
@CyberDem0n But the docs https://postgres-operator.readthedocs.io/en/latest/administrator/#google-cloud-platform-setup only mention: `gcp_credentials`, `wal_gs_bucket`, `additional_secret_mount_path`, `additional_secret_mount` and the pod env vars `USE_WALG_BACKUP`, `USE_WALG_RESTORE` and `CLONE_USE_WALG_RESTORE`: do I *also* need `WALE_GS_PREFIX` and `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by haf** [comment]
I guess my big question is:

What does this affect?

**Comment by CyberDem0n** [comment]
> What does this affect?

Google metadata affects absolutely nothing.  Only on AWS wal-e/wal-g can get S3 credential from instance metadata.

> But the docs https://postgres-operator.readthedocs.io/en/latest/administrator/#google-cloud-platform-setup only mention: gcp_credentials, wal_gs_bucket, additional_secret_mount_path, additional_secret_mount

Yes, because these docs are for postgres-operator, but after all operator maps its own settings to environment variables accepted by Spilo.

**Comment by haf** [comment]
> Google metadata affects absolutely nothing.

Thanks, that's a relief.

> these docs are for postgres-operator

Yes, I know they are for the operator, but since the operator does the mapping, isn't it the case that say `wal_gs_bucket` ought to set `WALE_GS_PREFIX` since the bucket is part of the prefix?

**Comment by CyberDem0n** [comment]
`wal_gs_bucket` should set `WAL_GS_BUCKET` and from there Spilo builds the `WALE_GS_PREFIX`: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L731-L749

In case if `WALE_GS_PREFIX` happened to be set as environment, Spilo will use it directly

**Comment by haf** [comment]
I'm closing because there's no negative effect of the reported issue.
