### ISSUE TITLE
2.0-p2 can not build image

### ISSUE THREAD

**Issue by necipakca** [zalando/spilo#528]
I can not build 2.0-p2 release with additional language.

Build process exit with code 2.

+ cd /usr/share/postgresql/12/contrib/postgis-3.0
/bin/sh: 1: cd: can't cd to /usr/share/postgresql/12/contrib/postgis-3.0

I added all build process log to attachment. 

[spilo_build.log](https://github.com/zalando/spilo/files/5721262/spilo_build.log)

**Comment by CyberDem0n** [comment]
This is due to the postgis 3.1 release.

**Comment by aditya1808** [comment]
How to resolve this now?

**Comment by mindw00rk** [comment]
Dockerfile:
ENV POSTGIS_VERSION=3.0 -> ENV POSTGIS_VERSION=3.1
${POSTGIS_VERSION%.0} -> ${POSTGIS_VERSION%.1}
