### ISSUE TITLE
Upgrade to PostGIS 3.1.0

### ISSUE THREAD

**Issue by boonen** [zalando/spilo#529]
On 18 December 2020 PostGIS 3.1.0 was released. This version has several important improvements with regard to performance, so I would like to see it included in the next Spilo release. For details see this blog post: <https://postgis.net/2020/12/18/postgis-3.1.0/>.

If you like I am willing to provide a pull request.

**Comment by CyberDem0n** [comment]
Closed in https://github.com/zalando/spilo/pull/535

**Comment by boonen** [comment]
@CyberDem0n Thanks for solving this issue so quickly!
