### ISSUE TITLE
Does Spilo support setting wal-g environment variables?

### ISSUE THREAD

**Issue by haslersn** [zalando/spilo#531]
In particular, I'm interested in whether Spilo supports setting `WALG_COMPRESSION_METHOD=lzma`.

**Comment by CyberDem0n** [comment]
Yes, most of wal-g settings are supported: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L690-L694

**Comment by haslersn** [comment]
Could you document this, please?

**Comment by CyberDem0n** [comment]
@haslersn this is an open-source project, anyone can contribute and document, please feel free to open a PR.
