### ISSUE TITLE
IPV6 Openstack metadata service, spilo 2.0-p2, /scripts/configure_spilo.py

### ISSUE THREAD

**Issue by Samusername** [zalando/spilo#541]
Hi! For possible discussion,

In spilo 2.0-p2, openstack IPV4 metadata service IP address is used:

        url = 'http://**169.254.169.254**/openstack/latest/meta_data.json'

/scripts/configure_spilo.py. [git master](https://github.com/zalando/spilo/tree/master/postgres-appliance/scripts).

It does not work when OpenStack uses IPV6.
IPV6 address for openstack metadata service [is available in Victoria](https://docs.openstack.org/nova/latest/admin/metadata-service.html), it seems. Address: fe80::a9fe:a9fe.

We use older openstack releases still.

Victoria:
https://releases.openstack.org/
Initial release date: 2020-10-14

**Comment by Samusername** [comment]
OpenStack in IPV6 network,
Following error was shown, when the DB cluster was tried to be started:
<details>
  <summary>Click to expand</summary>
  
  ## Error message
  /launch.sh
--> python3 /scripts/configure_spilo.py all
Fails:
Traceback (most recent call last):
  File "/scripts/configure_spilo.py", line 1012, in <module>
    main()
  File "/scripts/configure_spilo.py", line 890, in main
    placeholders = get_placeholders(provider)
  File "/scripts/configure_spilo.py", line 598, in get_placeholders
    placeholders['instance_data'] = get_instance_metadata(provider)
  File "/scripts/configure_spilo.py", line 392, in get_instance_metadata
    metadata['zone'] = openstack_metadata.availability_zone
AttributeError: 'dict' object has no attribute 'availability_zone'
  
</details>

( Just a ) Quick workaround:

return always:
```return PROVIDER_LOCAL```
from function: def get_provider(), in /scripts/configure_spilo.py.

Should that work as a quick workaround?
At least DB cluster starts up now.

**Comment by CyberDem0n** [comment]
It was fixed recently: https://github.com/zalando/spilo/pull/526.
You can build your own image from the master or use the `registry.opensource.zalan.do/acid/spilo-cdp-13:2.0-p150`
