### ISSUE TITLE
When the wal-g push is unsuccessful, it does not try to push the wal file again

### ISSUE THREAD

**Issue by z-yfgit** [zalando/spilo#563]
The wal-g tool cannot push wal files to the S3 storage service. After fixing the connection problem with S3, it will not automatically push wal files to the storage. The wal-g process will get stuck.
If I kill the process manually, it can be pushed back to S3.
But it's not advisable to kill the process manually, so I modified the /scripts/postgres_backup.sh script.

modify /scripts/postgres_backup.sh
from
```
...
# We reduce the priority of the backup for CPU consumption
exec nice -n 5 $WAL_E backup-push "$PGDATA" "${POOL_SIZE[@]}"
```
to
```
...
# We reduce the priority of the backup for CPU consumption
exec nice -n 5 **timeout 30** $WAL_E backup-push "$PGDATA" "${POOL_SIZE[@]}"
```

Is there a good solution?

**Comment by CyberDem0n** [comment]
`timeout 30` sets the 30 seconds timeout.
Think about backing up the 1TB cluster...
IMO, the issue should be fixed in the wal-g.

**Comment by z-yfgit** [comment]
Thank you！
My wal-file is only 16M，30seconds is enough.
I also think timeouts should be implemented in the wal-g.
Thanks

**Comment by CyberDem0n** [comment]
> My wal-file is only 16M，30seconds is enough.

You have been referring to `backup-push`, not `wal-push`.
Even in case of wal-push wal-g can push up to 1000 files at a time, what could clearly take longer than 30s.
