### ISSUE TITLE
A cordon of a node triggers a db failover

### ISSUE THREAD

**Issue by sabinematthys** [zalando/spilo#564]
With spilo 13 patroni 2.0 and postgres-operator 1.6.0 I noticed that when doing a cordon of master it triggers a db failover
Before cordon we have
```bash
| Member                   | Host          | Role    | State   | TL | Lag in MB |
+--------------------------+---------------+---------+---------+----+-----------+
| db-cluster-0 | ip1 | Replica | running | 35 |         0 |
| db-cluster-1 | ip2 | Leader  | running | 35 |           |
| db-cluster-2 | ip3 | Replica | running | 35 |         0 |
+--------------------------+---------------+---------+---------+----+-----------+
```
then I do 
`kubectl cordon $(kubectl get pods -l application=spilo -l spilo-role=master -o=jsonpath='{.items[0].spec.nodeName}')`
And after I see:

- just after:
```bash
| Member                   | Host          | Role    | State   | TL | Lag in MB |
+--------------------------+---------------+---------+---------+----+-----------+
| db-cluster-0 | ip1 | Leader  | running | 36 |           |
| db-cluster-1 | ip2 | Replica | stopped |    |   unknown |
| db-cluster-2 | ip3 | Replica | running |    |   unknown |
+--------------------------+---------------+---------+---------+----+-----------+
```

- a bit after:
```bash
| Member                   | Host          | Role    | State   | TL | Lag in MB |
+--------------------------+---------------+---------+---------+----+-----------+
| db-cluster-0 | ip1 | Leader  | running | 36 |           |
| db-cluster-1 | ip2 | Replica | stopped |    |   unknown |
| db-cluster-2 | ip3 | Replica | running | 36 |         0 |
+--------------------------+---------------+---------+---------+----+-----------+
```

- after stabilisation:
```bash
| Member                   | Host          | Role    | State   | TL | Lag in MB |
+--------------------------+---------------+---------+---------+----+-----------+
| db-cluster-0 | ip1 | Leader  | running | 36 |           |
| db-cluster-1 | ip2 | Replica | running | 36 |         0 |
| db-cluster-2 | ip3 | Replica | running | 36 |         0 |
+--------------------------+---------------+---------+---------+----+-----------+
```
So we see that just with a cordon the leader is on ip1 while it was on ip2 before.
This behavior affects our testing strategy (involving cordon of nodes to schedule pods on other nodes than master for instance) that was developed with Spilo 12 and Patroni 1.6.5 also we are not sure if it could have impact on upgrade of our application. 
Is there a way to deactivate the behaviour?

**Comment by CyberDem0n** [comment]
What is in Postgres-Operator and Spilo pod logs?
Patroni isn't doing a failover without a reason.

**Comment by sabinematthys** [comment]
time="2021-03-09T16:53:47Z" level=info msg="moving pods: node \"/cluster-c\" became unschedulable and does not have a ready label: map[]" pkg=controller
time="2021-03-09T16:53:47Z" level=info msg="starting process to migrate master pod \"db-cluster-0\"" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:47Z" level=debug msg="Waiting for any replica pod to become ready" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:47Z" level=debug msg="Found 2 running replica pods" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:47Z" level=info msg="check failed: pod \"db-cluster-1\" is already on a live node" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:47Z" level=debug msg="switching over from \"db-cluster-0\" to \"db-cluster-1\"" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:47Z" level=debug msg="making POST http request: http://<ip>:8008/failover" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:47Z" level=debug msg="subscribing to pod \"db-cluster-1\"" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:48Z" level=debug msg="successfully switched over from \"db-cluster-0\" to \"db-cluster-1\"" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:48Z" level=debug msg="unsubscribing from pod \"db-cluster-1\" events" cluster-name=db-cluster pkg=cluster worker=0
time="2021-03-09T16:53:48Z" level=info msg="1/1 master pods have been moved out from the \"/cluster-c\" node" pkg=controller

**Comment by sabinematthys** [comment]
It seems to me that just because the node becomes unschedulable it triggers a failover, it does it each time I cordon a node with master and which ever that node is. If I cordon all the nodes at the same time, it doesn't but a replica crashes.

**Comment by CyberDem0n** [comment]
You see? The switchover was triggered by the postgres-operator.
This is intentional behaviour, if the node is not schedulable it is moving spilo pods from it.

**Comment by sabinematthys** [comment]
Indeed, I think it is a new feature which I don't really understand as un-schedulable means **new** pods cannot be scheduled, why does it mean status of current ones have to be changed? 
In our case, we use the cordon to prevent pods to be scheduled on master (and I think it is pretty common), but that is just one among several ways we use cordon on master node, how can we do that if master swiches from node as soon as it is cordoned? So is there as way to disable that feature (we didn't have that problem in previous version)?

**Comment by sabinematthys** [comment]
But maybe what you mean is that the isssue should be opened somewhere else (postgres-operator level and not spilo), is it?

**Comment by CyberDem0n** [comment]
Operator always worked this way (moving spilo pods from nodes with disabled scheduling).
I think what you better do - create a dedicated nodepool for spilo.
And yes, you better ask it in the postgres-operator issues.

**Comment by sabinematthys** [comment]
In previous version, we didn't have the problem so I don't think it has always worked like that but whatever I will open an issue in postgres-operator then, thanks !
