### ISSUE TITLE
Certificate not created, only key

### ISSUE THREAD

**Issue by nyxi** [zalando/spilo#568]
If this is not the correct project for this issue please point me in the right direction :)

Recently bootstrap of new PostgreSQL clusters started failing in our environment. It seems like PostgreSQL is failing to start because the certificate is not created as it should be, but the key is:

```
2021-03-16 08:14:37 UTC [303]: [3-1] 605068ed.12f 0     FATAL:  could not load server certificate file "/run/certs/server.crt": No such file or directory

$ ls -l /run/certs
total 4
-rw------- 1 postgres root 1708 Mar 16 08:09 server.key
```

My suspicion is that this is because we are now mounting `/etc/ssl` and `/etc/pki` from the host in all containers. I would still like to understand why this is causing problems, ie how does Spilo generate the certificate?

I've attached the log from the pod:
[pod.log](https://github.com/zalando/spilo/files/6147223/pod.log)

**Comment by CyberDem0n** [comment]
This is how certificates/keys are handled: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L83-L116

If you mount them, you should also specify the location via `'SSL_CERTIFICATE_FILE` and `SSL_PRIVATE_KEY_FILE` environment variables.

There are also `SSL_CA_FILE` and `SSL_CRL_FILE`: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L254-L259

**Comment by nyxi** [comment]
Thanks!

After some quick testing it seems the Python script does not check that the openssl command completes successfully. If I run the openssl command manually I get:

```
# /usr/bin/openssl req -nodes -new -x509 -subj '/CN=spilo.example.org' -keyout server.key -out server.crt
Can't open /usr/lib/ssl/openssl.cnf for reading, No such file or directory
140291251204544:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('/usr/lib/ssl/openssl.cnf','r')
140291251204544:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
Generating a RSA private key
..................................................................................................................+++++
..................................+++++
writing new private key to 'server.key'
-----
unable to find 'distinguished_name' in config
problems making Certificate Request
140291251204544:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:../crypto/conf/conf_lib.c:270:
```

Which makes sense considering:

```
# ls -l /usr/lib/ssl/openssl.cnf
lrwxrwxrwx 1 root root 20 Dec  2 14:54 /usr/lib/ssl/openssl.cnf -> /etc/ssl/openssl.cnf

# stat /etc/ssl/openssl.cnf
stat: cannot stat '/etc/ssl/openssl.cnf': No such file or directory
```

So our "overwriting" of `/etc/ssl` and `/etc/pki` is definitely to blame. Might be a good idea to check the return code of the openssl command for success though.

**Comment by CyberDem0n** [comment]
Since you provide already existing cert and key the openssl should not be executed at all: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L94-L96

**Comment by nyxi** [comment]
I did a bad job explaining what we are doing and why. We mount the host's `/etc/pki` and `/etc/ssl` directories in all containers to make sure they have our internal CA:s. So we don't get TLS errors when connecting to our internal HTTPS endpoints.

For Spilo/Postgres in this context we still want Spilo to generate its own certificates if possible, which I think we can achieve by "fixing" `/etc/ssl/openssl.cnf` on our end.
