### ISSUE TITLE
Failing backup-cron and no logs?

### ISSUE THREAD

**Issue by PetterSa** [zalando/spilo#569]
I upgraded to the newest postgres-operator and for some reason the cron with `postgres_backup.sh` seems to fail. But not when running it manually. I am not sure how to debug this as I can't find the logs from the cron job. Any help on where to look for errors would be appreciated :)

**Comment by CyberDem0n** [comment]
The simplest you can do - edit crontab (`crontab -e -u postgres`) and add log redirection to a file.

**Comment by PetterSa** [comment]
Alright, thanks :) 
But there is no logging today then? Would it be valuable to make a PR that logs the result to somewhere, like stdout?

**Comment by PetterSa** [comment]
Seems like we had some problems running with the runasuser and runasgroup settings in kubernetes? We didn't need them so the problem is fixed for us, but it seems weird. The launch script failed with 

```
/launch.sh: 24: /launch.sh: cannot create /etc/passwd: Permission denied
```

Patroni started booting after this, but cron never started and exited with error code 1 when trying to run the service manually. 🤷‍♂️

Anyway, this is solved enough for me so I will close this.
