### ISSUE TITLE
What is the difference between the Postgres official image and any of the images here?

### ISSUE THREAD

**Issue by mnishizawa** [zalando/spilo#570]
**Situation**:
I am using the same code running against the docker official postgres image running in docker compose (postgres:12.5) vs the 1.6-p3 all the way up to 2.0-p5 and I encounter a similar situation in each case.

When I execute my code against the database running in docker compose, it succeeds.  The queries all work as expected and return an expected result.  When I run it against the database using any of the spilo images, it fails.  It's not a failure as in terms of an error, but the code gets a different output result which is incorrect. 

I've tried ensuring the collations are the same.  I've ensured that the data is the same.  The code is the same.  This happens regardless of the OS the code is running on.

The only discernable differences I can see are minor version:

Working :
`postgres=# select version();
version|PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`

\l
`Name|my_test
Owner|postgres
Encoding|UTF8
Collate|en_US.utf8
Ctype|en_US.utf8
Access privileges|`

vs

Not working:
`postgres=# select version();
version|PostgreSQL 12.6 (Ubuntu 12.6-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit`

\l
`Name|my_test
Owner|postgres
Encoding|UTF8
Collate|en_US.UTF-8
Ctype|en_US.UTF-8
Access privileges|`

What I'm really looking for are any differences in configuration or anything else that might be different between the version of the database you are producing and the official postgres:12.5 image.

**Comment by CyberDem0n** [comment]
Postgres image from the dockerhub is based on Debian (don't know which version), while Spilo is based on Ubuntu 18.04 and contains all postgres versions starting from 9.5 to 13.

If you think that your issue is related to collation, probably it would make sense to read https://wiki.postgresql.org/wiki/Locale_data_changes
