### ISSUE TITLE
Unable to create timescaledb extension

### ISSUE THREAD

**Issue by Kumar6295** [zalando/spilo#591]
hi,
We try to create timescaledb extension in database but getting error like below

**ERROR**
 extension "timescaledb" must be preloaded
Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: home/postgres/pgdata/pgroot/data/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
# Modify postgresql.conf:
shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
**echo "shared_preload_libraries = 'timescaledb'" >>home/postgres/pgdata/pgroot/data/postgresql.conf**

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with:
SET timescaledb.allow_install_without_preload = 'on';

we added using echo command , after  that try to restart patroni using patronictl command at the time added shared_preload_libraries  removed.
How we can add shared libraries.

**Comment by CyberDem0n** [comment]
I am not sure what mage you use, but timescaledb is added to the shared_preload_libraries for a few years already.

**Comment by Kumar6295** [comment]
Thanks for reply.
We are using helm chart with below repo
  repository: registry.opensource.zalan.do/acid/spilo-10
  tag: 1.5-p5
  pullPolicy: IfNotPresent
