### ISSUE TITLE
Database Connection Error while using in Application

### ISSUE THREAD

**Issue by Kumar6295** [zalando/spilo#594]
Hi,
We are using repository: registry.opensource.zalan.do/acid/spilo-13,tag: 2.0-p6 for patroni.Patroni cluster is working fine.
Try to connect for out  side of the pod (actually server)using ip and port able to connect and create database,Working fine.

root@k8smaster:/opt# psql -h 10.233.64.19 -p 5432 -d test_db -U postgres
Password for user postgres: 
test_db=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test_db   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres         +
           |          |          |             |             | postgres=CTc/postgres

(4 rows)

**While using same ip and port,username,password in application.it is giving below error.**
ip:10.233.64.19
port:5432
username:postgres
password : postgres

**ServerIP: 62.21.184.225 (kubenetes,kubectl etc running)**

**ERROR** we don't have any running pod and endpoints  in this ip 10.233.64.4

Connection fails: error: pg_hba.conf rejects connection for host "10.233.64.4", user "postgres", database "test_db", SSL off

**Cluster status**

root@patroni-cluster-0:/home/postgres# patronictl -c /home/postgres/.config/patroni/patronictl.yaml list
+ Cluster: patroni-cluster (6981382670454915142) ------+----+-----------+
| Member            | Host         | Role    | State   | TL | Lag in MB |
+-------------------+--------------+---------+---------+----+-----------+
| patroni-cluster-0 | 10.233.64.19 | Leader  | running |  2 |           |
| patroni-cluster-1 | 10.233.64.37 | Replica | running |  2 |         0 |
| patroni-cluster-2 | 10.233.64.38 | Replica | running |  2 |         0 |
+-------------------+--------------+---------+---------+----+-----------+

using **patronictl -c /home/postgres/.config/patroni/patronictl.yaml  edit-config** command,added below line.
pg_hba:  host all          all         0.0.0.0/0        trust
listen_addresses: "*"
after added restarted using below command
**patronictl -c /home/postgres/.config/patroni/patronictl.yaml  restart patroni-cluster**

**kubectl pod details**
patroni-cluster-0                                  1/1     Running   0          54m     10.233.64.19   k8smaster     <none>           <none>
patroni-cluster-1                                  1/1     Running   0          54m     10.233.64.37   k8smaster     <none>           <none>
patroni-cluster-2                                  1/1     Running   0          54m     10.233.64.38   k8smaster     <none>           <none>
patroni-cluster-etcd-0                             1/1     Running   0          54m     10.233.64.22   k8smaster     <none>           <none>
patroni-cluster-etcd-1                             1/1     Running   0          54m     10.233.64.31   k8smaster     <none>           <none>
patroni-cluster-etcd-2                             1/1     Running   0          54m     10.233.64.39   k8smaster     <none>           <none>

**kubectl endpoint details**

patroni-cluster                                          10.233.64.19:5432                                                   55m
patroni-cluster-config                                   <none>                                                                 94m
patroni-cluster-etcd                                     10.233.64.22:2380,10.233.64.31:2380,10.233.64.39:2380 + 3 more...   55m
patroni-cluster-etcd-ns                                  10.233.64.22:2380,10.233.64.31:2380,10.233.64.39:2380 + 3 more...   55m

**Comment by CyberDem0n** [comment]
> ERROR we don't have any running pod and endpoints in this ip 10.233.64.4

And? How this is the Spilo issue?
