### ISSUE TITLE
How the certificate rotation/renew works?

### ISSUE THREAD

**Issue by mygithubthrowaway** [zalando/spilo#603]
Hi there,

thanks for this wonderful project!

I have just a curiosity (I did a search here and docs without be able to find the exact answer)
We are testing the zalando operator without adding any custom certificate in the cluster crd.
For what I understand the spilo image can generate and renew a self-generated certificate right?

Indeed I'm seeing in a spilo pod:

```
$ ls -l /run/certs
total 8
-rw-r--r-- 1 postgres postgres 1135 Jul 25 11:01 server.crt
-rw------- 1 postgres postgres 1704 Jul 25 11:01 server.key
$ openssl x509 -in /run/certs/server.crt --noout --enddate
notAfter=Aug 24 11:01:20 2021 GMT
```
this cluster was created on July 25 and the cert will expire on 24 august.
Now the questions: 
* when and how will be renewed? 
* how the renew will works when that spilo pod is a leader? will be performed a failover to reload the new certificate? 

thanks!

**Comment by CyberDem0n** [comment]
> can generate and renew a self-generated certificate right?

generate - yes, renew - no

One should understand that self-signed certificates don't provide a proper security.

From the Postgres perspective the certificate change doesn't require a restart starting from v9.6

**Comment by mygithubthrowaway** [comment]
> > can generate and renew a self-generated certificate right?
> 
> generate - yes, renew - no

Oh I see, thanks.

> One should understand that self-signed certificates don't provide a proper security.

I know but even if the certificate is expired if I have the `sslmode != verify-ca|verify-full` will not affect the connection to my db right? So for not production env could be ok

> From the Postgres perspective the certificate change doesn't require a restart starting from v9.6

Ok thanks

also can you point me to the code here where the generation will be performed?

**Comment by CyberDem0n** [comment]
> if I have the sslmode != verify-ca|verify-full will not affect the connection to my db right?

With sslmode=require it doesn't check the expiration date.

> can you point me to the code here where the generation will be performed?

https://github.com/zalando/spilo/blob/21fa3f176d6704589cae2938866ad04dc1c42cea/postgres-appliance/scripts/configure_spilo.py#L93-L113

**Comment by mygithubthrowaway** [comment]
thanks a lot!
