### ISSUE TITLE
postgres.yml was not updated when pod was recreated

### ISSUE THREAD

**Issue by wqhhust** [zalando/spilo#604]
After I set up spilo on kubernete with 3 nodes, and then delete/create the pods many times, later I get the following inconsistent status. The root cause is the init script after docker started (/launch.sh) doesn't update postgres.yml.
So I am wondering whether we need to have a specific parameter like overwrite_patronic_configure to overwrite the file every time. Or a better way is to by default check the current ip, and if the current ip doesn't match with  postgres.yml, then modify it, and run patronictl to reload all. If you think the second way is the right thing to do, I can create a PR

postgres@postgreql-stateful-set-0:~$ patronictl list
+ Cluster: postgreql-stateful-set (6988389289585311823) --------+----+-----------+
| Member                   | Host          | Role    | State    | TL | Lag in MB |
+--------------------------+---------------+---------+----------+----+-----------+
| postgreql-stateful-set-0 | 10.10.80.91   | Leader  | running  | 10 |           |
| postgreql-stateful-set-1 | 10.123.172.59 | Replica | stopped  |    |   unknown |
| postgreql-stateful-set-2 | 10.10.80.92   | Replica | starting |    |   unknown |
+--------------------------+---------------+---------+----------+----+-----------+
postgres@postgreql-stateful-set-0:~$ cat /etc/hosts
10.10.80.92	postgreql-stateful-set-0

**Comment by CyberDem0n** [comment]
> delete/create the pods many times, later 

Something is fishy. When you delete the pod it also deletes the container and the new pod has the new container.
If the config file continues to exist that means the pod wasn't deleted.

**Comment by wqhhust** [comment]
In my environment, all the files except the ones on mounted data volumes are not writable, so I mounted /run to a PVC, and since the configurate file is a link to /run/postgres.yml, so it is persistiable. After we delete/create it, the file is already there.

**Comment by CyberDem0n** [comment]
> so I mounted /run to a PVC

Please use tmpfs for that.
