### ISSUE TITLE
not working in k3s

### ISSUE THREAD

**Issue by viorel-anghel** [zalando/spilo#610]
I'm trying to use Zalando Postgres Operator in a K3S cluster. It is working perfectly in a KIND (Kubernetes in docker) cluster. 

To reproduce the problem, you need to setup a k3s cluster in a Ubuntu VM. Basically the steps are
```
# read https://k3s.io/
curl -sfL https://get.k3s.io | sh -

# install kubectl and helm
...

# setup kubeconfig
mkdir -p .kube ; ln -s /etc/rancher/k3s/k3s.yaml .kube/config
kubectl get nodes

# install postgres operator
cd postgres-operator
helm install postgres-operator ./charts/postgres-operator
kubectl get pods

# setup postgres minimal cluster
kubectl apply -f manifests/minimal-postgres-manifest.yaml
```

This will fail (but it works perfectly in KIND cluster). The postgresql pods will never get the master/replica role. In the end, the operator status (`kubectl get postgresql`) will show `STATUS: SyncFailed`.

The postgres pod logs show something like:
```
...
initdb: error: could not access directory "/home/postgres/pgdata/pgroot/data": Permission denied
```

Inspecting the pod, the directory /home/postgres/pgdata have permissions 0700 with owner root, which means the user postgres cannot go "inside" and that explains the initdb error.

This can be very easy avoided with a simple modification in launch.sh with a `chmod 0755 /home/postgres/pgdata`, after the line `mkdir -p "$PGLOG"...`. I did this and tested the new image and now it works perfectly under both clusters.

I wasn't able to explain why this directory has those permissions when running under K3S, but 0777 permissions when running under KIND or simply under Docker.

**Comment by CyberDem0n** [comment]
The [launch.sh](https://github.com/zalando/spilo/blob/master/postgres-appliance/launch.sh#L35-L38) is supposed to change permissions of the pgroot, but for some reason it is not the case for you.

I afraid you will have to debug it on your own.

**Comment by viorel-anghel** [comment]
those lines are changing permissions on
+ chown -R postgres: /home/postgres/pgdata/pgroot /run/certs
+ chmod -R go-w /home/postgres/pgdata/pgroot
+ chmod 01777 /run/tmp
+ chmod 0700 /home/postgres/pgdata/pgroot/data

But the problem is the parent directory /home/postgres/pgdata which sometimes apprae to be 0700 owner root.

**Comment by CyberDem0n** [comment]
> But the problem is the parent directory /home/postgres/pgdata which sometimes apprae to be 0700 owner root.

Well, you didn't even show enough logs, or debug information, so I can't comment.
Don't expect that someone will debug it for you.

**Comment by viorel-anghel** [comment]
I did and I found a simple solution which works for me. That single line addition in launch.sh `chmod 0755 /home/postgres/pgdata`. I'm still investigating why this is necessary in the k3s case.

**Comment by CyberDem0n** [comment]
I think `0711` should be enough.

**Comment by ToonvanStrijp** [comment]
@viorel-anghel you can also solve this by using a different image for your k3s cluster. I don't know what they changed... but the image below works just fine.
```
 k3d cluster create test --image rancher/k3s:v1.21.2-k3s1
```

**Comment by viorel-anghel** [comment]
It can be also solved with init containers in the operator. leaving this here just in case anyone interested:

spec:
[... existing stuff ...]  
  initContainers:
  - name: chmod
    image: busybox
    command: [ "/bin/sh"]
    args: [ "-c", "chmod 711 /home/postgres/pgdata" ] 
    volumeMounts:
    - name: pgdata
      mountPath: /home/postgres/pgdata
