### ISSUE TITLE
building minimal spilo image 

### ISSUE THREAD

**Issue by asafo** [zalando/spilo#611]
Hello

Going over the Dockerfile, There are alot of extensions being installed, (e.g: timescale)
What is the absolute minimum required pg extensions for Spilo operation ?
(for running on k8s using the postgres operator)

Thanks

**Comment by CyberDem0n** [comment]
Most of these extensions take very little space in the image and don't hurt performance I don't see any single reason for investing to build the image without them.

**Comment by sasadangelo** [comment]
I have a question related to the extensions too.
I am working on a project where we are migrating Patroni from traditional infrastructure to Kubernetes.
In our original cluster, the only extension we use is 
```
  SPILO_CONFIGURATION: |
    bootstrap:
      dcs:
        ...
        postgresql:
          ...
          parameters:
            ...
            shared_preload_libraries: pg_stat_statements
```

but when I deploy Spilo in the Pod logs I see the following:
```
ERROR:  unrecognized configuration parameter "cron.database_name"
CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF
ERROR:  extension "pg_cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
ERROR:  schema "cron" does not exist
```

so it seems that Spilo requires ```pg_cron``` and I cannot avoid inserting it. Am I correct? Should I always activate pg_cron in Spilo even if I don't need it?
Spilo by default uses the following extensions ```bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user```, is there a way to only use pg_stat_statements and avoid failure into the code?

**Comment by CyberDem0n** [comment]
If you go this way, you also need to modify scripts, for example, the post_init.sh: https://github.com/zalando/spilo/blob/62d5293df82be487eb14004c77a8a8dd9891655b/postgres-appliance/scripts/post_init.sh#L42-L76
