### ISSUE TITLE
Possible mismatch for PGROOT in the Spilo code

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#619]
Hi all,

In my Kubernetes YAML I assumed that the following variables have the relative default I am mentioning:
```
PGHOME=/home/postgres
PGROOT=PGHOME/pgroot
PGDATA=PGROOT/pgdata
```

This is confirmed by the following code:
* https://github.com/zalando/spilo/blob/62d5293df82be487eb14004c77a8a8dd9891655b/postgres-appliance/scripts/configure_spilo.py#L470
* https://github.com/zalando/spilo/blob/62d5293df82be487eb14004c77a8a8dd9891655b/postgres-appliance/scripts/configure_spilo.py#L475
* https://github.com/zalando/spilo/blob/62d5293df82be487eb14004c77a8a8dd9891655b/postgres-appliance/scripts/configure_spilo.py#L477

However, I noticed that Spilo in other places uses different defaults:
* https://github.com/zalando/spilo/blob/62d5293df82be487eb14004c77a8a8dd9891655b/postgres-appliance/Dockerfile#L456
* https://github.com/zalando/spilo/blob/62d5293df82be487eb14004c77a8a8dd9891655b/postgres-appliance/bootstrap/maybe_pg_upgrade.py#L12

The effect that I see is that Spilo creates the folder ```~/pgroot/pgdata/data``` to store the PostgreSQL data directory and the ```~/pgdata/pgroot/pgdata/pg_log``` and for some reason I don't understand I got some permission issues on this folder:

```
PermissionError: [Errno 13] Permission denied: '/home/postgres/pgdata/pgroot/data'
/run/service/patroni: finished with code=1 signal=0
/run/service/patroni: exceeded maximum number of restarts 5
stopping /run/service/patroni
timeout: finish: .: (pid 163) 8s, want down
```

while I suppose that this folder ```/home/postgres/pgdata/pgroot/data``` should not be used because the real one is ```/home/postgres/pgroot/pgdata/data```.

**Comment by CyberDem0n** [comment]
Ref: https://github.com/zalando/spilo/issues/469

**Comment by sasadangelo** [comment]
Ok, let me do the question in a different way.
What should I do if I want to change, at runtime, the value of the PostgreSQL data directory?

**Comment by CyberDem0n** [comment]
> Does Spilo allow to customize it?

We never cared about this case.

**Comment by sasadangelo** [comment]
Ok, thank you. You can close this issue.

**Comment by robinp** [comment]
Slightly other usecase: FYI for running a podman compose example with directory mounts, this works:

```
mkdir spilo1_data spilo2_data spilo3_data
podman unshare chown 101 spilo1_data spilo2_data spilo3_data
podman unshare chmod 750 spilo1_data spilo2_data spilo3_data
```
with
```
volume:
    ./spiloN_data:/home/postgres/pgdata
```
