### ISSUE TITLE
Restore using wal-g does not work

### ISSUE THREAD

**Issue by Delorien84** [zalando/spilo#622]
Hello,
 I have notice that when I want to restore database using `wal-g` , I got error message: `Can not find any backups`. When switch to `wal-e` it works properly. Problem is in https://github.com/zalando/spilo/blob/62d5293df82be487eb14004c77a8a8dd9891655b/postgres-appliance/scripts/wale_restore.sh#L44 where given expression does not find anything when using `wal-g`. I have check that manually executing `wal-g backup-list` properly finds all backups.

Using `registry.opensource.zalan.do/acid/spilo-13:2.1-p1` docker image as default in current version (1.7.0) of https://github.com/zalando/postgres-operator

**Comment by CyberDem0n** [comment]
Yes, and it was fixed in the `registry.opensource.zalan.do/acid/spilo-cdp-13:2.1-p184`
