### ISSUE TITLE
Syctl commands wont run Error with sysctl: setting key "<>": Read-only file system

### ISSUE THREAD

**Issue by kish3007** [zalando/spilo#623]
Base ubuntu:18.04 image is used and the commands in launch.sh shell script fails and redirected to null :

sysctl -w vm.dirty_background_bytes=67108864 # > /dev/null 2>&1
sysctl -w vm.dirty_bytes=134217728 #> /dev/null 2>&1

only workaround when creating a cluster using this image, use initcontaienrs and set  sysctl commands needed.

**Comment by CyberDem0n** [comment]
These commands are just best effort tuning for containerized systems with limited memory.
If they fail the container will still start.
