### ISSUE TITLE
The fix for wal-g 1.1 header should be applied to the script /scripts/postgres_backup.sh too

### ISSUE THREAD

**Issue by gandalfmagic** [zalando/spilo#631]
Hi, the script `/scripts/postgres_backup.sh` uses the wrong sed command in case we use `wal-g` as backup tool.
In such case, the old backups are not deleted as intended.

You shoul fix the script with the regex:

```bash
done < <($WAL_E backup-list 2> /dev/null | sed '0,/^name\s*\(last_\)\?modified\s*/d')
```

**Comment by CyberDem0n** [comment]
Good catch, please create a PR.

**Comment by gandalfmagic** [comment]
Created PR #632
