### ISSUE TITLE
Question: init custom users and databases

### ISSUE THREAD

**Issue by sayf-eddine-scality** [zalando/spilo#639]
Hello, I am trying to use Spilo as a database for keycloak, but I cannot find a clean way to pre-create the database for keycloak as it expects the user and the database to be created for it.
I am using a bash script as `post_bootstrap.sh` to do that but it can't be used in conjunction with users created in `initdb` section. as the bash scripts is executed before the user is created (so I had to also create the user in the script).
Am I missing something? I tried to go through all the doc for Spilo and Patroni but couldn't find anything.

PS: sorry if this is not a good format for an issue, I didn't find a template.

**Comment by CyberDem0n** [comment]
> it can't be used in conjunction with users created in initdb section. as the bash scripts is executed before the user is created

It was a terrible idea to create arbitrary users from Patroni. IMO, this "feature" should be non-existent. My advice would be - just do everything from the post_bootstrap script.

**Comment by sayf-eddine-scality** [comment]
Alright thanks.
