### ISSUE TITLE
"add_retention_policy" is not supported under the current "apache" license

### ISSUE THREAD

**Issue by chandrakanth515** [zalando/spilo#645]
Hi,

I am using "spilo-cdp-13:2.0-p171" version of PostgreSQL . I have enabled timescale dB . TimescaledbVersion : 2.2.1.

I want to use "add_retention_policy" . When I was trying to use add_retention_policy I am seeing  below errors.

  function "add_retention_policy" is not supported under the current "apache" license
  Upgrade your license to 'timescale' to use this free community feature

Can anyone help with this?

**Comment by CyberDem0n** [comment]
You have to build your own image: https://github.com/zalando/spilo/#how-to-build-this-docker-image
