### ISSUE TITLE
Please add timescaledb into default shared_preload_libraries for PG14

### ISSUE THREAD

**Issue by Delorien84** [zalando/spilo#666]
Hello,
 I have notice, that `timescaledb` is not present in default `shared_preload_libraries` when using PG14, prevent us to use PG14 with `timescaledb`. Could you please add it?

Is there any way how to append `timescaledb` to `shared_preload_libraries`? When I set `shared_preload_libraries` in `SPILO_CONFIGURATION` it completely override `shared_preload_libraries` and not keeping the default one.

**Comment by CyberDem0n** [comment]
Yes, it was clearly forgotten: https://github.com/zalando/spilo/blob/f8179d9a5de5e9a78e5a447130f759f97811879b/postgres-appliance/scripts/spilo_commons.py#L15
But, you have all the power to open a PR fixing it.
