### ISSUE TITLE
add first_last_agg extension to image

### ISSUE THREAD

**Issue by ibotty** [zalando/spilo#672]
It would be great to have the small extension first_last_agg, available on apt.postgresql.org, also in spilo.  Would you consider a pull request adding it?

**Comment by CyberDem0n** [comment]
Yes, please open a PR

**Comment by ibotty** [comment]
I am also using Citus.  I assume that extension is a a little too invasive to include, right?  Its installation is compatible with apt.postgresql.com but needs an additional repository (and corresponding pgp key) and adds about 7MB afaict.

**Comment by CyberDem0n** [comment]
Having Citus extension would be also interesting.
Do you know if they also provide arm64 packages?

**Comment by ibotty** [comment]
Does not look like it:  https://github.com/citusdata/citus/issues/3854
Would it be acceptable to conditionally add the citus on the supported architectures?
