### ISSUE TITLE
Cron Service not Necessarily Started when Mounting Crontabs

### ISSUE THREAD

**Issue by haslersn** [zalando/spilo#678]
During my work on my recent PR, I probably discovered a logic error in `configur_spilo.py`: The log written in line

https://github.com/zalando/spilo/blob/bd0179fed5f453d2b4dc5be409a2d410589cdff5/postgres-appliance/scripts/configure_spilo.py#L885

suggests that it's supported to manually configure cron, e.g. by mounting the crontab(s) into the container. However, due to the check

https://github.com/zalando/spilo/blob/bd0179fed5f453d2b4dc5be409a2d410589cdff5/postgres-appliance/scripts/configure_spilo.py#L948

the cron process is only started if spilo *would hypothetically* configure at least one cron job, even if one manually configures cron by mounting a crontab into the container. What is the intended behavior? I see two options:

- If it's supported to mount crontabs, then the cron process should be started if at least one crontab is present.
- If it's not supported to mount crontabs, then `check_crontab` can be entirely eliminated from the script.

**Comment by CyberDem0n** [comment]
> suggests that it's supported to manually configure cron, e.g. by mounting the crontab(s) into the container. 

Nope, this is only a protection against the second run of the configure_spilo.py
