### ISSUE TITLE
Vulnerabilities found in Spilo-14:2.1-p3 Image using Twistlock

### ISSUE THREAD

**Issue by Arun-Trichy** [zalando/spilo#687]
Hi Team

We are using Spilo Image as part of Zalando-Postgres Operator in one of our projects. 
In a recent Twistlock scan report it was found that the spilo-14:2.1-p3 Image is having a CRITICAL vulnerability.

**Type:** Twistlock
**Compliance ID:** 448
**Severity:** critical
**Description:** Package binaries should not be altered
**Cause:** Altered binaries: /usr/lib/postgresql/13/bin/pg_checksums, /usr/lib/postgresql/14/bin/pg_checksums

Is there any plan to fix this ? Or has this been fixed in any latest releases ? 
Can you explain what's the problem in Spilo Image causing this vulnerability ?

Thanks
Arun

**Comment by CyberDem0n** [comment]
postgresql-*-pg-checksum packages are just installed from pgdg repo, there is nothing altered. 

I have very little idea what your tool does (and how), but from my experience, all kinds of tools for scanning images are producing too many false positives that discard their usefulness.

In any case, nobody forces you to use provided images. Feel free to build/use your own.
