### ISSUE TITLE
Spilo image with UBI base image

### ISSUE THREAD

**Issue by pratapagiri** [zalando/spilo#692]
Is there a plan to support Spilo docker image with UBI base image [ubi8](https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e) 

Can someone suggest what changes are needed for this?

**Comment by CyberDem0n** [comment]
> Is there a plan to support Spilo docker image with UBI

No, there is too many differences between Debian/Ubuntu and RedHat

> Can someone suggest what changes are needed for this?

More or less everything

**Comment by pratapagiri** [comment]
Thanks @CyberDem0n
