### ISSUE TITLE
PATRONI_POSTGRESQL_CONNECT_ADDRESS and PATRONI_NAME not working

### ISSUE THREAD

**Issue by v4nTh3M4n** [zalando/spilo#695]
Tested on Spilo Version **latest**, **2.1-p3**, **2.0-p7**.

I used the Docker file to create a docker Spilo image, and then ran the container with certain ENV VARIABLES supported by Spilo and Patroni. Somehow the variables PATRONI_POSTGRESQL_CONNECT_ADDRESS and PATRONI_NAME are not picked up by Spilo. 

`docker build --build-arg=PGVERSION="13" --build-arg=PGOLDVERSIONS="11" -t spilo .`

`docker run -d -e PGVERSION="11" -e PATRONI_POSTGRESQL_CONNECT_ADDRESS="hostname:5432" -e PATRONI_NAME="randomname" -e SCOPE="clustername" -e PATRONI_SCOPE="clustername" -p 5432:5432 spilo`

The ENV variables are in the container (using docker exec [containername] env), but the automatically created postgres.yml file does not reflect the values from passed environment variables when starting the container.
Shouldn't the Spilo image be able to use or pass on the Patroni specific ENV variables when passed through a docker run?

Instead of the container ID as member name, I want to pass it the container name. And instead of the container IP address, I want it to use the docker hostname and portnumber.

_Regarding the scope - I needed to pass both PATRONI_SCOPE and the SCOPE ENV variables for the cluster rename from dummy to clustername to work. If not passed both the new cluster wil be passed to ETCD, but the patroni configuration does not know about it._

**Comment by CyberDem0n** [comment]
Spilo has its own env variables: https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst
