### ISSUE TITLE
/.../runsvdir/.../patroni/run: file permissions have been changed? _____ Re: Groups of user does not contain "0(root)" anymore ...

### ISSUE THREAD

**Issue by Samusername** [zalando/spilo#701]
Original topic was: "Groups of user does not contain "0(root)" anymore --> ./run: access denied"

I am using default "Endpoints" setup of postgres-operator, in this test.

Hi!

We tried to use new version of spilo: [2.1-p4](https://github.com/zalando/spilo/releases/tag/2.1-p4).
--> registry.opensource.zalan.do/acid/spilo-14:2.1-p4

For some reason, our container in our pod starts up with following permissions, "id":
uid=101(postgres) gid=103(postgres) groups=**103(postgres)**

It does not have "root" group permissions anymore.
That causes access denied errors, when e.g. patroni tries to start up:

runsv pgqd: fatal: unable to start ./run: access denied
runsv patroni: fatal: unable to start **./run: access denied**

Permissions of run:
postgres@rdbms-pg-cluster-0:/etc/runit/runsvdir/default/patroni$ ls -ltrh
total 8.0K
-rwxr-x---. 1 **root** **root** 834 Feb 21 14:34 run

With a previous version of spilo, 2.1-p3, output of "id" contained e.g. "0(root)":
postgres@rdbms-pg-cluster-0:~$ id
uid=101(postgres) gid=103(postgres) groups=103(postgres),**0(root)**,102(ssl-cert)

E.g. such supplemental group is not shown anymore when we are using new spilo-14:2.1-p4.
We took only such new version of spilo in use in this test. Otherwise other definitions and versions remained the same.

What could cause this?

**Comment by CyberDem0n** [comment]
> What could cause this?

I don't know, there is nothing changed in Spilo in this area.
This is what I see:
```
$ id
uid=101(postgres) gid=103(postgres) groups=103(postgres),0(root),102(ssl-cert)

```

**Comment by Samusername** [comment]
Only to experiment:
I tried to edit Statefulset of our DB cluster directly manually. 
I added "0" to supplementalGroups there:

```
securityContext: 
    ...
    supplementalGroups: [0]
```
    
( Such is not supported by the tools. So, this is only an experiment to try to learn more. )

--> Then the "0(root)" is shown. 
But there must be something else here.

**Comment by Samusername** [comment]
https://github.com/zalando/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml
--> Same happens with such acid-minimal-cluster.
Works ok with spilo-14:2.1-p3. 
The mentioned error occurs with spilo-14:2.1-p4.

I am using default "Endpoints" setup of postgres-operator.

Next, I will try to possibly try with various configurations of postgres-operator (values.yaml). -- I try to do a sort of "Binary search" / "half-interval search" in finding a possible root cause.

**Comment by Samusername** [comment]
Two checks.

# spilo_runasgroup

We had value "103" in spilo_runasgroup yesterday. We removed it for testing purposes now.

```
  spilo_fsgroup: 103
  spilo_runasuser: 101
  # spilo_runasgroup: 103 # This line was removed now today

  spilo_privileged: false
  spilo_allow_privilege_escalation: false
```
In DB cluster manifest yaml, there were following entries:
  spiloRunAsUser: 101
  spiloFSGroup: 103

By default spilo_runasgroup is possibly root. 
Such explains also the text "0(root)" in the output of "id" command.
"0(root)" comes visible then.
The DB cluster starts up also then.

# File permissions of "run":

Difference between p3 and p4:

spilo-14:2.1-p3:

> root@d004c056e940:/# ls -ltrh /etc/runit/runsvdir/default/patroni/run
> **-rwxrwxrwx** 1 root root 834 Oct 28 07:04 /etc/runit/runsvdir/default/patroni/run

spilo-14:2.1-p4:

> ls -ltrh /etc/runit/runsvdir/default/patroni/run
> **-rwxr-x---** 1 root root 834 Feb 21 14:34 /etc/runit/runsvdir/default/patroni/run

Such have changed now?

**Comment by CyberDem0n** [comment]
It could be related to https://github.com/zalando/spilo/blob/76101a9fa9d0de4d45a94c8fdc8f2c90c410e9af/postgres-appliance/Dockerfile#L527

Please try to change permissions to `755`.

**Comment by max-kuklin** [comment]
The same here, had to remove `runAsGroup: 103` from manifest to get it to work with new image `spilo-14:2.1-p4`.
