### ISSUE TITLE
sv restart patroni does not restart - only stop 

### ISSUE THREAD

**Issue by v4nTh3M4n** [zalando/spilo#702]
Using the `sv restart patroni` command will only stop patroni, but not start it again.

A workaround is using `sv stop patroni` and `sv start patroni`, but restart should also work imo.
Also, running `sv restart patroni` twice does of course also work as it will stop the service the first time and start it the second time.

**Comment by CyberDem0n** [comment]
That might be true, but it is not really important.
There are absolutely 0 cases when restart is required.

**Comment by v4nTh3M4n** [comment]
Then I would suggest removing it from the motd.

```
 ____        _ _
/ ___| _ __ (_) | ___
\___ \| '_ \| | |/ _ \
 ___) | |_) | | | (_) |
|____/| .__/|_|_|\___/
      |_|

This container is managed by runit, when stopping/starting services use sv

Examples:

sv stop cron
sv restart patroni

```

**Comment by CyberDem0n** [comment]
Maybe, one day..
