### ISSUE TITLE
Q. Exclusion of timescaledb extension from Dockerfile --> Major version upgrade fails

### ISSUE THREAD

**Issue by Samusername** [zalando/spilo#703]
Hi! 
Tag: Question.

We tried to exclude timescaledb from Dockerfile of Spilo.
DB cluster worked with such setup. Minor version upgrade worked also. (It seems.)

Major version upgrade fails, with following error message:  
FATAL:  could not access file "timescaledb": No such file or directory
( At least such error is shown. )

Q1: Should I modify one of scripts from following directory?
https://github.com/zalando/spilo/tree/master/postgres-appliance/major_upgrade
Or possibly from somewhere else?

I am currently trying to analyze such files.

I am trying to execute automatic Major version upgrade, PG 13.6 --> PG 14.2,
with following settings in postgres-operator:
```
configMajorVersionUpgrade:
  major_version_upgrade_mode: "full"
  minimal_major_version: "14"
  target_major_version: "14"
```

Major version upgrade works fine, if timescaledb extension is included.
So, I am suspecting there is something in Major version upgrade, related to it (timescaledb).

Q2: Btw., is timescaledb optional? In Spilo.

Q3: What is your recommendation: should we try to keep timescaledb extension related files in our spilo image?
We do not enable such extension in our setups.

<details>
  <summary>Some more logs. Click to expand!</summary>
cat /home/postgres/pgdata/pgroot/data_upgrade/pg_upgrade_server.log

-----------------------------------------------------------------
  pg_upgrade run on Fri Mar 18 07:29:32 2022
-----------------------------------------------------------------

command: "/usr/lib/postgresql/13/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/home/postgres/pgdata/pgroot/data" -o "-p 50432 -c autovacuum=off -c autovacuum_freeze_max_age=2000000000  -c listen_addresses='' -c unix_socket_permissions=0700" start >> "pg_upgrade_server.log" 2>&1
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2022-03-18 07:29:32 UTC [246]: [1-1] 623434dc.f6 0     FATAL:  lock file "postmaster.pid" already exists
2022-03-18 07:29:32 UTC [246]: [2-1] 623434dc.f6 0     HINT:  Is another postmaster (PID 64) running in data directory "/home/postgres/pgdata/pgroot/data"?
 stopped waiting
pg_ctl: could not start server
Examine the log output.

command: "/usr/lib/postgresql/14/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/home/postgres/pgdata/pgroot/data_new" -o "-p 50432 -b -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c vacuum_defer_cleanup_age=0 -c timescaledb.restoring='false' -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/home/postgres/pgdata/pgroot/data_upgrade'" start >> "pg_upgrade_server.log" 2>&1
waiting for server to start....2022-03-18 07:29:32 UTC [274]: [1-1] 623434dc.112 0     LOG:  pgaudit extension initialized
2022-03-18 07:29:32 UTC [274]: [2-1] 623434dc.112 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2022-03-18 07:29:32 UTC [274]: [3-1] 623434dc.112 0     LOG:  pg_stat_kcache.linux_hz is set to 500000
2022-03-18 07:29:32 UTC [274]: [4-1] 623434dc.112 0     **FATAL:  could not access file "timescaledb": No such file or directory**
2022-03-18 07:29:32 UTC [274]: [5-1] 623434dc.112 0     LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.

</details>

**Comment by CyberDem0n** [comment]
It seems that you are not using the latest spilo image.

**Comment by Samusername** [comment]
I tried to build it from Dockerfile of version 2.1-p4. I tried to exclude timescaledb there.
https://github.com/zalando/spilo/tags --> 2.1-p4 (zip).
I used files from following directory to build it: [postgres-appliance](https://github.com/zalando/spilo/tree/76101a9fa9d0de4d45a94c8fdc8f2c90c410e9af/postgres-appliance)

I could retry the same.

Or is that (postgres-appliance) correct way / directory to try to build it? With "docker build .".

**Comment by CyberDem0n** [comment]
Well, since you modified the dockerfile now it is your responsibility.
Right now timescaledb is added to the shared_preload_libraries and probably therefore everything fails.
You may try to "disable" it here: https://github.com/zalando/spilo/blob/76101a9fa9d0de4d45a94c8fdc8f2c90c410e9af/postgres-appliance/scripts/spilo_commons.py#L15

**Comment by Samusername** [comment]
> shared_preload_libraries 
 
 Ok. Thanks for the hint!
 
 Let's see should we try to stick to use the original Dockerfile of Spilo, without excluding timescaledb.
