### ISSUE TITLE
tar xz etcd -- Building with rootless docker image, gives error still

### ISSUE THREAD

**Issue by Samusername** [zalando/spilo#708]
( Sorry. We had time to set our building systems up only now, to verify following issue. )

"rootless": building in image/container which does not have/use a root linux user

Continuation from:
https://github.com/zalando/spilo/issues/704  --> https://github.com/zalando/spilo/pull/707 --> https://github.com/zalando/spilo/commit/01c8361794ea80e8cf7a5b4bdbc1bdaecb37024b

Row 77, originally in spilo 2.1-p4:

```
                | tar xz -C /bin --strip=1 --wildcards --no-anchored etcdctl etcd; \
```
--> pull/707:
```
                | tar xz -C /bin --strip=1 --wildcards --no-anchored etcdctl etcd \
        && chown root:root /bin/etcd*; \
```

That gives still the same original error in our building job:

```
tar: etcdctl: Cannot change ownership to uid 114762, gid 114762: Invalid argument
tar: etcd: Cannot change ownership to uid 114762, gid 114762: Invalid argument
```

Following "**--no-same-owner**" option seems to help:

```
                | tar xz -C /bin --strip=1 --wildcards --no-anchored --no-same-owner etcdctl etcd \
        && chown root:root /bin/etcd*; \
```

**Comment by CyberDem0n** [comment]
Feel free to open a PR.
