### ISSUE TITLE
Provide a mapping for Postgres minor versions provided by a Spilo release

### ISSUE THREAD

**Issue by thedatabaseme** [zalando/spilo#709]
Hello,

maybe I just looked at the wrong place, but I wasn't able to find anything like this. When having a look into the Spilo release page here on Github, I'm not able to see directly, which minor version of Postgres will get provided (for the respective major version) with a new Spilo release.

Something like this in the release description would help in my opinion:

| Major version | Minor version |
| ----------- | ----------- |
| 14      | 14.2       |
| 13   | 13.6        |
| 12   | ...        |

Is there anything like this and I haven't looked properly?

Kind regards
Philip

**Comment by CyberDem0n** [comment]
You can safely assume that we always use the latest minor versions.

**Comment by thedatabaseme** [comment]
But wouldn't it make sense anyway for having an overview which Spilo image uses which minor for history reasons? Maybe someone wants to use a specific PG version or Spilo release for any reason. And it's not much effort to provide this information is it?
