### ISSUE TITLE
Select specific timeline during restore possible?

### ISSUE THREAD

**Issue by thedatabaseme** [zalando/spilo#712]
Hello,

I've raised this also over @ the Zalando Operator repo. During some restore tests, we tried to restore to a specific timeline (using the operator CRDs). Which is not implemented as it turns out. But having a look into the Spilo images, it seems that the recovery.conf parameter `recovery_target_timeline` is not adjustable. Can you clarify if my understanding is correct? If so, it confuses me, cause using timelines during restores seems a quite basic concept for a database, although there are not many occasions were you need it.

Thanks in advance for clarification. See the issue on the operator repo [here](https://github.com/zalando/postgres-operator/issues/1832).

Kind regards
Philip

**Comment by CyberDem0n** [comment]
Yes, now it is hardcoded to the `latest`.
If you want to make it configurable please create a PR.
But, IMO, the default should remain the `latest`.

**Comment by thedatabaseme** [comment]
If this would be in my possibilities, I would do so. But believe me, I'm the last person you want to have doing things in the code :)

**Comment by CyberDem0n** [comment]
Well, before PR is merged it has to pass automatic tests and be reviewed by two engineers.
