### ISSUE TITLE
Adding extra extensions into the image

### ISSUE THREAD

**Issue by philmccOri** [zalando/spilo#715]
Hi,
I would like to use the ApacheAGE extension with my install that is using the spilo image. 
What is the best way to get this extension added into the image or made available?
I am actually using the zolando postgres operator in case that makes a difference.

Thanks

**Comment by philmccOri** [comment]
https://age.apache.org/#

**Comment by TacoNaco47** [comment]
Hey @philmccOri 

I was wondering about pretty much the same question, as I need the `pgjwt` extension for my Postgres containers (Supabase). But if you look at the [Dockerfile on line 198](https://github.com/zalando/spilo/blob/2daefafc666da0c44ce1f030e65cc2d10ab3f7ed/postgres-appliance/Dockerfile#L198), you could probably add your extension there. 

As stated in the [operator documentation](https://postgres-operator.readthedocs.io/en/latest/reference/operator_parameters/), they encourage you to build an own Spilo image for production. 

> docker_image Spilo Docker image for Postgres instances. For production, don't rely on the default image, as it might be not the most up-to-date one. Instead, build your own Spilo image from the [github repository](https://github.com/zalando/spilo). 

Maybe one from the Dev team can confirm this?

**Comment by bbedward** [comment]
I added `pgjwt` by modifying the appliance/build_scripts/base.sh , here's a gist of the blurb i updated

https://gist.github.com/bbedward/839801372862c67fb894f98db80f59d1

just cloned pgjwt and copied files into the relevant folders.

Also I pushed a spilo image to our docker hub, which is just the latest (at time of writing) + pgjwt , which can be used for supabase self-host.

https://hub.docker.com/r/stablecog/spilo
