### ISSUE TITLE
Python lxml security vulnerability

### ISSUE THREAD

**Issue by carroarmato0** [zalando/spilo#725]
When building the spilo container (with TimescaleDB license) I noticed that one of the python packages has been found to contain a high security vulnerability.  GHSA-55x5-fj6c-h6m8+lxml

HIGH Vulnerability found in non-os package type (python) - lxml (fixed in: 4.6.5)(cvss_v3_base_score=7.1)(GHSA-55x5-fj6c-h6m8 - https://github.com/advisories/GHSA-55x5-fj6c-h6m8)

I think it's indirectly pulled through PIP.

**Comment by CyberDem0n** [comment]
Packages are either installed as standard Ubuntu packages with apt-get or with pip3.
In both cases latest possible versions are installed.

But, for example Ubuntu packages sometimes get these vulnerabilities backpatched, without changing the package version (only suffix get changed). I believe that could trigger a false positive of security scanners.

In fact, in my experience, docker security scanners create a lot of false positives. Sometimes they report vulnerabilities in packages that are not even installed.
