### ISSUE TITLE
Final release of PostgreSQL 9 (9.6) was reached in Nov 2021

### ISSUE THREAD

**Issue by TooExtremeSecurity** [zalando/spilo#733]
Priority: minor minor

Others have mentioned following. I am only forwarding this on behalf of them.

PostgreSQL 9 (9.6) has reached final release.
May some projects still use it?

If yes, then it may need to be included in spilo for some time still.
Otherwise such final release release 9.x of PostgreSQL could be removed from spilo.

BR: "Sometimes too much security"

**Comment by CyberDem0n** [comment]
We already have a plan to remove it from the image

**Comment by kallitu** [comment]
Do you have a release plan schedule?
