### ISSUE TITLE
wal-g backup fails on large basebackups with more than 999 parts

### ISSUE THREAD

**Issue by steav** [zalando/spilo#734]
Hi,

I am facing the issue that wal-g full base backup (brotli compressed) stops after 999 parts; as soon as `tar_partitions/part_999.tar.br` gets uploaded to S3.

A workaround is to double up `WALG_TAR_SIZE_THRESHOLD` from 1GB to 10GB, which reduces the number of parts from slightly over 1000 to 130.
But this causes high RAM usage during backup push and leads to postgres oomkills on my K8s cluster. Therefore 5GB threshold atm.

I am using spilo `2.1-p5` with zalando operator and timescaledb.

**Comment by CyberDem0n** [comment]
> am facing the issue that wal-g full base backup (brotli compressed) stops after 999 parts; as soon as tar_partitions/part_999.tar.br gets uploaded to S3.

Well, I am quite sure wal-g was working just fine with clusters that are more than 1TB in size and with a default value of `WALG_TAR_SIZE_THRESHOLD`.

In any case I don't see it like a problem with Spilo. You better open an issue in wal-g repo if it is really the case.

**Comment by steav** [comment]
Yes right, more wal-g related.
