### ISSUE TITLE
What is the general patching policy? Create new spilo image for PostgreSQL-14.4 on June 16.

### ISSUE THREAD

**Issue by lucianvlad** [zalando/spilo#739]
Hello,
I would like to know what is your general patching policy?
I am asking this as there is a [bug](https://www.migops.com/blog/2022/06/09/important-postgresql-14-update-to-avoid-silent-corruption-of-indexes/) in all current versions of PostgreSQL-14 
The patch for this bug will be released on June 16-th and I would like to know what is your policy regarding this critical bug/security fixes and how long will it take until you release a new Spilo image with the PostgreSQL-14.4 
Thank you
Best Regards
Lucian

**Comment by CyberDem0n** [comment]
We are also affected by this bug and will build the new image ASAP.
It will be immediately available as `spilo-cdp-14`. Tagging the production image may take a couple of days.
