### ISSUE TITLE
Unable to boostrap when using Patroni 1.0

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/spilo#74]
With 84cadfb23621136ab271d3e463e318979792e948 Spilo is bumped to Patroni 1.0.

However, when boostrapping a new cluster, it loops in trying to bootstrap without leader using wal-e:

```
2016-07-06 14:23:37,613 ERROR: could not query wal-e latest backup: Command '['envdir', '/home/postgres/etc/wal-e.d/env', 'wal-e', '--aws-instance-profile', 'backup-list', '--detail', 'LATEST']' returned non-zero exit status 1
2016-07-06 14:23:37,636 ERROR: failed to bootstrap (without leader)
2016-07-06 14:23:37,636 INFO: Removing data directory: /home/postgres/pgdata/data
```

When removing the `create_replica_method` altogether from the yaml it also loops waiting for the leader to bootstrap:

```
2016-07-06 14:26:55,435 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-06 14:26:55,435 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-06 14:26:55,435 INFO success: pgq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-06 14:27:04,431 INFO: waiting for leader to bootstrap
2016-07-06 14:27:14,431 INFO: waiting for leader to bootstrap
2016-07-06 14:27:24,431 INFO: waiting for leader to bootstrap
2016-07-06 14:27:34,432 INFO: waiting for leader to bootstrap
```

contents of etcd at time of looping:

``` json
{
    "action": "get",
    "node": {
        "createdIndex": 80081,
        "dir": true,
        "key": "/service/dummy",
        "modifiedIndex": 80081,
        "nodes": [
            {
                "createdIndex": 80081,
                "dir": true,
                "key": "/service/dummy/members",
                "modifiedIndex": 80081,
                "nodes": [
                    {
                        "createdIndex": 80114,
                        "expiration": "2016-07-06T14:29:24.431983611Z",
                        "key": "/service/dummy/members/42644697d238",
                        "modifiedIndex": 80114,
                        "ttl": 29,
                        "value": "{\"role\":\"uninitialized\",\"state\":\"stopped\",\"conn_url\":\"postgres://172.17.0.2:5432/postgres\",\"api_url\":\"http://172.17.0.2:8008/patroni\"}"
                    }
                ]
            }
        ]
    }
}
```

The problem is not with Patroni 1.0 per se: Using the Docker image from the Patroni repo works as expected (members are bootstrapped)

**Comment by alexeyklyukin** [comment]
Hi,

> On 06 Jul 2016, at 17:29, Feike Steenbergen <notifications@github.com> wrote:
> 
> With 84cadfb <https://github.com/zalando/spilo/commit/84cadfb23621136ab271d3e463e318979792e948> Spilo is bumped to Patroni 1.0.
> 
> However, when boostrapping a new cluster, it loops in trying to bootstrap without leader using wal-e:
> 
> 2016-07-06 14:23:37,613 ERROR: could not query wal-e latest backup: Command '['envdir', '/home/postgres/etc/wal-e.d/env', 'wal-e', '--aws-instance-profile', 'backup-list', '--detail', 'LATEST']' returned non-zero exit status 1
> 2016-07-06 14:23:37,636 ERROR: failed to bootstrap (without leader)
> 2016-07-06 14:23:37,636 INFO: Removing data directory: /home/postgres/pgdata/data

The bootstrap without the leader only happens if the initialize key was already there for the cluster one tries to bootstrap.

> When removing the create_replica_method altogether from the yaml it also loops waiting for the leader to bootstrap:
> 
> 2016-07-06 14:26:55,435 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2016-07-06 14:26:55,435 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2016-07-06 14:26:55,435 INFO success: pgq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2016-07-06 14:27:04,431 INFO: waiting for leader to bootstrap
> 2016-07-06 14:27:14,431 INFO: waiting for leader to bootstrap
> 2016-07-06 14:27:24,431 INFO: waiting for leader to bootstrap
> 2016-07-06 14:27:34,432 INFO: waiting for leader to bootstrap
> contents of etcd at time of looping:
> 
> {
>     "action": "get",
>     "node": {
>         "createdIndex": 80081,
>         "dir": true,
>         "key": "/service/dummy",
>         "modifiedIndex": 80081,
>         "nodes": [
>             {
>                 "createdIndex": 80081,
>                 "dir": true,
>                 "key": "/service/dummy/members",
>                 "modifiedIndex": 80081,
>                 "nodes": [
>                     {
>                         "createdIndex": 80114,
>                         "expiration": "2016-07-06T14:29:24.431983611Z",
>                         "key": "/service/dummy/members/42644697d238",
>                         "modifiedIndex": 80114,
>                         "ttl": 29,
>                         "value": "{\"role\":\"uninitialized\",\"state\":\"stopped\",\"conn_url\":\"postgres://172.17.0.2:5432/postgres\",\"api_url\":\"http://172.17.0.2:8008/patroni\"}"
>                     }
>                 ]
>             }
>         ]
>     }
> }

Is this everything? Because either the “initialize” key is missing from the output above, or it is not created at all, which is really strange, since it’s literally the first thing that gets created when the cluster initializes….


Kind regards,
--
Oleksii Kliukin | 5432 Engineer | phone: +4917612759799 |  hipchat: @OleksiiKliukin

**Comment by feikesteenbergen** [comment]
We should incorporate the new configuration style in Spilo for Patroni >= 1.0. Going to work on that.

**Comment by alexeyklyukin** [comment]
> On 11 Jul 2016, at 13:28, Feike Steenbergen <notifications@github.com> wrote:
> 
> We should incorporate the new configuration style in Spilo for Patroni >= 1.0. Going to work on that.
> 
> 

The outdated configuration format doesn’t really explain why did it loop waiting for the master to start. You sure you didn’t reuse the cluster name accidentally?

Kind regards,
--
Oleksii Kliukin | 5432 Engineer | phone: +4917612759799 |  hipchat: @OleksiiKliukin

**Comment by LappleApple** [comment]
Hey @alexeyklyukin @CyberDem0n, can we close this issue?

**Comment by CyberDem0n** [comment]
Obsolete
