### ISSUE TITLE
Build a new docker image

### ISSUE THREAD

**Issue by machine424** [zalando/spilo#740]
Hello,

The new PG minor versions fix some bugs (https://git.postgresql.org/gitweb/?p=postgresql.git&a=commitdiff&h=e5691cc9170bcd6c684715c2755d919c5a16fea2 that we encounter with 14.2), I would like to know if you're planning on rebuilding the docker image (I see other dependencies were updated on maqter)

We re-built the image from [22c9247](https://github.com/zalando/spilo/commit/22c9247cb9c8d226fe16545673bbc6d419f4d07c), we'll leave it run for a moment and keep you in touch.

**Comment by CyberDem0n** [comment]
`registry.opensource.zalan.do/acid/spilo-cdp-14` images are built and tested for every commit to the master branch.
The image isn't pushed to the docker registry if tests are failing.
After running `spilo-cdp` for a few days we sometimes tag it as `registry.opensource.zalan.do/acid/spilo-14`.

For you it is more or less safe to build images from the master branch.

And speaking of REINDEX/CREATE INDEX CONCURRENTLY fixes - the new release will happen in about 6 hours and our plan is to immediately trigger the new build of `spilo-cdp-14`.

**Comment by machine424** [comment]
Hello,

Ok for the "test" registry, I don't think we want to document this.

It was not for the index corruption problem, but for a fix that had landed in 14.3.

**Comment by ibotty** [comment]
I don't see the new postgresql release in `spilo-14`.  In fact the latest image is still running postgresql-14.2 (latest is 14.4, but 14.3 is out for a bit now).

There are also some known security issues in the base package.  Is one supposed to build one's own image and keep it up-to-date?
