### ISSUE TITLE
Azure backups fail to complete in spilo-14:2.1-p6

### ISSUE THREAD

**Issue by walkbooth** [zalando/spilo#743]
When running spilo-14:2.1-p6 in an AKS cluster via the postgres operator, I can exec into a running pod and start a backup manually with this command:

```
envdir "/run/etc/wal-e.d/env" /scripts/postgres_backup.sh "/home/postgres/pgdata/pgroot/data"
```

However, the backup seems to get stuck, never moving past the `Calling pg_stop_backup()` log message:

```
2022-06-22 17:08:34.816 - /scripts/postgres_backup.sh - I was called as: /scripts/postgres_backup.sh /home/postgres/pgdata/pgroot/data
2022-06-22 17:08:34.956 - /scripts/postgres_backup.sh - producing a new backup
INFO: 2022/06/22 17:08:35.005656 Calling pg_start_backup()
INFO: 2022/06/22 17:08:35.645221 Starting a new tar bundle
INFO: 2022/06/22 17:08:35.645254 Walking ...
INFO: 2022/06/22 17:08:35.645578 Starting part 1 ...
INFO: 2022/06/22 17:08:35.900894 Packing ...
INFO: 2022/06/22 17:08:35.902092 Finished writing part 1.
INFO: 2022/06/22 17:08:36.398543 Starting part 2 ...
INFO: 2022/06/22 17:08:36.398577 /global/pg_control
INFO: 2022/06/22 17:08:36.407265 Finished writing part 2.
INFO: 2022/06/22 17:08:36.407287 Calling pg_stop_backup()
```

I cannot reproduce this on a postgres cluster using spilo-14:2.1-p5 and the same command:

```
2022-06-22 18:17:14.291 - /scripts/postgres_backup.sh - I was called as: /scripts/postgres_backup.sh /home/postgres/pgdata/pgroot/data
2022-06-22 18:17:14.463 - /scripts/postgres_backup.sh - producing a new backup
INFO: 2022/06/22 18:17:14.502348 Selecting the latest backup as the base for the current delta backup...
INFO: 2022/06/22 18:17:14.520890 Calling pg_start_backup()
INFO: 2022/06/22 18:17:14.722144 Starting a new tar bundle
INFO: 2022/06/22 18:17:14.722173 Walking ...
INFO: 2022/06/22 18:17:14.722396 Starting part 1 ...
INFO: 2022/06/22 18:17:15.158707 Packing ...
INFO: 2022/06/22 18:17:15.158946 Finished writing part 1.
INFO: 2022/06/22 18:17:15.798094 Starting part 2 ...
INFO: 2022/06/22 18:17:15.798136 /global/pg_control
INFO: 2022/06/22 18:17:15.805326 Finished writing part 2.
INFO: 2022/06/22 18:17:15.806011 Calling pg_stop_backup()
INFO: 2022/06/22 18:17:16.952639 Starting part 3 ...
INFO: 2022/06/22 18:17:17.157215 backup_label
INFO: 2022/06/22 18:17:17.157300 tablespace_map
INFO: 2022/06/22 18:17:17.157365 Finished writing part 3.
INFO: 2022/06/22 18:17:17.437986 Wrote backup with name base_000000040000000000000042
```

Aside from the different Docker image being used, there are no differences in configuration or data. I also don't see this issue on our AWS EKS clusters running this new version of spilo. Looking at the [release notes](https://github.com/zalando/spilo/releases/tag/2.1-p6) for 2.1-p6, could this be related to the upgrade to wal-g v2.0.0?

**Comment by CyberDem0n** [comment]
> could this be related to the upgrade to wal-g v2.0.0?

Maybe, I'll leave it to you to figure out.

**Comment by pawmar** [comment]
I encountered the same issue. Postgres logs have this message:
```
ERROR: 2022/07/21 08:46:47.441900 Error of background uploader: Couldn't check whether there is an overwrite attempt due to inner error: Azure error : Unable to download blob yyy-postgres/14/wal_005/000000080000000000000016.partial.lz4.: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR: 2022/07/21 08:46:47.443523 Couldn't check whether there is an overwrite attempt due to inner error: Azure error : Unable to download blob yyy-postgres/14/wal_005/00000007.history.lz4.: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```
It looks like insufficient permissions, which is strange as few seconds before the scrript managed to write several backup files to an azure container.

**Comment by Mahagon** [comment]
We encountered the same issue in wal-g 2.0 in our environment and i opened an issue for the wal-g project

https://github.com/wal-g/wal-g/issues/1322

**Comment by tomasz-zylka** [comment]
same question: when can we expect wal-g 2.0.1 to be included in newest spilo p7 image?

**Comment by hughcapet** [comment]
Hello lovely people! We are currently going through a process of responsibilities transition in this project. As soon as it finishes, we will initiate a new release containing the newest WAL-G version and other enhancements (thus, we probably will bind it to the upcoming pg15 release). I also promise to have a clearer release policy in the future.
As a workaround I can suggest building an alternative image from the master branch which already includes WAL-G 2.0.1.

**Comment by tomasz-zylka** [comment]
@hughcapet thanks for the information and update :+1: 
how stable the master branch is? I mean how risky it is to build an alternative image from the master branch which already includes WAL-G 2.0.1? ;)

**Comment by hughcapet** [comment]
@tomasz-zylka @b0n541 Here it is :)
https://github.com/zalando/spilo/releases/tag/2.1-p7
