### ISSUE TITLE
Python 3.6 is EOL and nastily hard coded into Dockerfile

### ISSUE THREAD

**Issue by NiiloNeuvo** [zalando/spilo#747]
Wearing the security hat here. Python 3.6 is EOL and as such will not receive security updates any more. I could only find a few smallish CVEs for 3.6. Upgrade to 3.9 or newer would be reducing potential problems longer term. 

There are some rather nasty looking patching happening in the Dockerfile which made it too scary for our team to touch this:
- [postgres-appliance/Dockerfile#L432-L440](https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L432-L440)
Are the wall-e patches really needed in 2022 to make Python upgrades in the future easier?

I guess this could be looked into after PR #746 (refactoring of Dockerfile) is completed.

**Comment by CyberDem0n** [comment]
Python 3.6 comes with Ubuntu 18.04 (and hence considered as supported). We are not going to upgrade python without changing the base docker image.
Changing ubuntu version to a new one could be even more tricky due to collation changes in glibc: https://wiki.postgresql.org/wiki/Locale_data_changes

**Comment by CyberDem0n** [comment]
> Cleaning the 3.6 hard coding from wall-e might still be a good move in order to prepare for a newer Python eventually?

This hard-coded version is actually our smallest problem. I am afraid that something more serious could pop up.

**Comment by NiiloNeuvo** [comment]
Should this be left open as a reminder about this needing attention eventually?

**Comment by NiiloNeuvo** [comment]
Closing this. Pointless to keep issues like these open in my view.
