### ISSUE TITLE
Question about spilo base OS

### ISSUE THREAD

**Issue by olivejing** [zalando/spilo#763]
Hi expert,

From postgres-appliance/Dockerfile, it uses ubuntu as base OS, Does it support Centos or Rocky as base OS?

**Comment by hughcapet** [comment]
No, it doesn't

**Comment by olivejing** [comment]
Thanks for your response.
Another question, i need to use centos/rocky as base to rebuild spilo image. If i modify some commands in Dockerfile to adapt centos, does it work?
From postgres-appliance/dependencies/debs, there are two files: libgdal20_2.2.3+dfsg-2_amd64.deb and libgdal20_2.2.3+dfsg-2_arm64.deb, is there any impact to my rebuild with centos as base?

**Comment by v4nTh3M4n** [comment]
@hughcapet, piggybacking this, how about the Ubuntu version. Are there any plans on moving away from 18.04 LTS to a newer version? Like 20 LTS or 22 LTS?

**Comment by CyberDem0n** [comment]
@v4nTh3M4n have you already seen https://wiki.postgresql.org/wiki/Locale_data_changes ?

**Comment by v4nTh3M4n** [comment]
The way I understand it is that changing the OS on existing databases will break stuff. How about new ones? Would that mean a spilo Docker image witch a newer OS version will not be supported at all in the future?

**Comment by hughcapet** [comment]
No, we will try to move to 22, hopefully, in the near future.
