### ISSUE TITLE
Spilo should set the cluster_name for 9.5+

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/spilo#77]
It would make it easier to identify a cluster from a DB connection:

See https://www.depesz.com/2014/07/02/waiting-for-9-5-add-cluster_name-guc-which-is-included-in-process-titles-if-set/

**Comment by feikesteenbergen** [comment]
Seems like we already did this:

> cluster_name - is set either from scope or from PATRRONI_SCOPE environment variable

https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst
