### ISSUE TITLE
Support SPN for wal-g backups to Azure Blob Storage

### ISSUE THREAD

**Issue by stephan2012** [zalando/spilo#775]
Currently, `wal-g` authenticates to Azure Blob Storage with a Storage Account key (`AZURE_STORAGE_ACCESS_KEY`). However, `wal-g` also supports [authentication with a Service Principal](https://github.com/wal-g/wal-g/blob/master/docs/STORAGES.md#azure), which is, in general, more desirable because it allows more fine-grained access control. 

Please add passing the environment variables `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, and `AZURE_TENANT_ID` to `wal-g`. For clarity, it might be an option to pass either `AZURE_STORAGE_ACCESS_KEY` or the SPN variables.

**Comment by hughcapet** [comment]
Unfortunately, Azure-related tasks are not a top priority for us now, thus this is unlikely to be implemented in the near future. However all contributions are welcomed.
