### ISSUE TITLE
Postgresql 13 Compatibility

### ISSUE THREAD

**Issue by whitepiratebaku** [zalando/spilo#776]
Hello, can you please clearify if spilo-14:2.1-p6 is compatible with PostgreSQL 13?

**Comment by hughcapet** [comment]
Hello.
What do you mean by "compatible with PostgreSQL 13"? 
FYI: You can always influence which version is bootstrapped by setting PGVERSION [env variable](https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst). For spilo-14 you can choose from: 9.6 10 11 12 13 14

**Comment by whitepiratebaku** [comment]
It is like we are using spilo-13 currently with PostgreSQL 13 and need to upgrade to spilo-14, we can easly do it without PostgreSQL upgrade right?

**Comment by hughcapet** [comment]
Yes, it is right
