### ISSUE TITLE
Not an issue but rather a question - Is it possible to have a postgres extension called 'credcheck' in Spilo? This extension is more than a nice to have as it can help defining various complexities for password  and user creation.

### ISSUE THREAD

**Issue by Sudeepta92** [zalando/spilo#791]
The extension: https://github.com/MigOpsRepos/credcheck

**Comment by hughcapet** [comment]
Unfortunately, we currently are not interested in adding this extension to Spilo

**Comment by Sudeepta92** [comment]
Maybe it doesn't even require anything in the bootstrap and implementation could be easier than we thought initially.
