### ISSUE TITLE
install aws_s3 extension

### ISSUE THREAD

**Issue by ibotty** [zalando/spilo#798]
Would you consider installing the PostgreSQL extension [`aws_s3`](https://github.com/chimpler/postgres-aws-s3)?  I would submit a pull request.

**Comment by hughcapet** [comment]
Unfortunately, no. It is highly unlikely that we will include extensions that are not installed from pgdg repository (unless they are highly demanded)

**Comment by ibotty** [comment]
Makes sense.  Thank you for your reply.
