### ISSUE TITLE
Find a way to encrypt secrets, i.e usernames/passwords/keys on K8S

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/spilo#80]
Basically the equivalent to KMS on AWS, but running on GCE/K8S, and plug it in to Spilo.

**Comment by ram-argus** [comment]
Isn't it better to let K8s take care of [hiding its secrets](https://github.com/kubernetes/kubernetes/issues/12742)?

AFAIK, k8s secrets is the expected way for storing credentials

**Comment by alexeyklyukin** [comment]
Yes, that's what we are doing currently with the Helm chart (yet unreleased), reading those variables from the secret file.
