### ISSUE TITLE
WAL-G Zstd compression seems to be unavailable

### ISSUE THREAD

**Issue by EraYaN** [zalando/spilo#808]
Gives the error: 

```failed to configure compression: Unknown compression method, supported methods are: [lz4 lzma brotli]```

when trying to set `WALG_COMPRESSION_METHOD` to `zstd`. The WAL-G project still seems to ship zstd, they even moved to a full Go implementation about a week ago, is there a reason the spilo image does not ship it?

**Comment by hughcapet** [comment]
As far as I understand, zstd compression is not yet included into any WAL-G release. Spilo uses the latest release version, not the current state of WAL-G project's master branch

**Comment by EraYaN** [comment]
Aah I assumed it would have shipped already since the code in WAL-G is from 2018 and the latest release was much more recent. Like this is the original PR: https://github.com/wal-g/wal-g/pull/99

**Comment by hughcapet** [comment]
and it was disabled in 2018: https://github.com/wal-g/wal-g/commit/a27a2a96adf47bf20e15e0cc2e0b917cf6044131
returned only recently: https://github.com/wal-g/wal-g/commit/25616a7bb9855349a429179aeee2480839fcd43b

**Comment by EraYaN** [comment]
Aah that is unfortunate, we'll go run Brotli in the mean time.

**Comment by gabrielmocan** [comment]
#986 will fix that 😄

**Comment by gabrielmocan** [comment]
@EraYaN I can confirm zstd is now working after #986

Cheers!
