### ISSUE TITLE
Expected release date of the next stable spilo image?

### ISSUE THREAD

**Issue by yoshihikoueno** [zalando/spilo#817]
Hello,
Thank you for maintaining this great project.

Given that PostgreSQL 15 support is now added to the master branch (#794),
I'm very excited to see the next stable release, which I assume to be tagged `spilo-15:2.***`.

I'm aware that there's an image tagged `spilo-cdp-15:2.1-p253`, but I'm still wondering when would the sable one get released.

**Comment by hughcapet** [comment]
Hello. We are planning to tag the new release in about a week, after we finish testing `spilo-cdp-15` internally

**Comment by yoshihikoueno** [comment]
@hughcapet 
I noticed that `spilo-15:p9` is now released.
Thank you for that.

**Comment by hughcapet** [comment]
@yoshihikoueno, yes. Sorry for not informing you, was in the holiday rush:)
