### ISSUE TITLE
Set etcd timeout in single node deployment

### ISSUE THREAD

**Issue by gabrielmocan** [zalando/spilo#836]
It is possible to allow setting ETCD_TIMEOUT value as a ENV?

When I try to set it via SPILO_CONFIGURATION, it disables local etcd entirely.

**Comment by hughcapet** [comment]
First of all, what is `ETCD_TIMEOUT`?:)

As for the second part of your message - it is correct, if you set any ETCD_* or any other dcs-specific config parameter, it will disable local provider: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L1068-L1070. This local etcd was added for the tests in the first place.

**Comment by gabrielmocan** [comment]
Okay I'll put in some background. I'm using Spilo with swarm, and I have some edge cases that I can't afford to have multiple nodes to run a full fledge Spilo cluster. In those cases I still use Spilo due to its facilities like s3 backups and in-place pg_upgrade. So I run in local mode with local etcd.

Everything goes fine but in some situations I get moments of bad performance of client's VMs and local etcd takes a little longer to respond, throwing some warnings like:

2023-02-01 22:06:42,410 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=2379): Read timed out. (read timeout=3.33319117835102)",)': /v2/keys/service/U001_CNTO_UAI/leader

And if that situation persists for 3 consecutive times (that's also hard-coded, 3 timeouts of 3 seconds) -- the following happens:

Request to server http://localhost:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'localhost\', port=2379): Max retries exceeded with url: /v2/keys/service/U001_CNTO_UAI/status (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'localhost\', port=2379): Read timed out. (read timeout=3.3330637123338724)",))',)
spilo_spilo.1.jfdpch0mfazs@CNTO-UAI-MANAGER    | 2023-02-01 22:45:10,349 INFO: Reconnection allowed, looking for another server.

So giving this context, I would like to be able to edit this etcd timeout parameter from 3s to any value suited for the desired scenario, while still using the local etcd bundled with Spilo in the same container.

That's possible by passing thru SPILO_CONFIGURATION, like:

etcd:
  host: 127.0.0.1:2379
  timeout: 5

But when doing so, local etcd is disabled as expected.

**Comment by hughcapet** [comment]
> etcd:
host: 127.0.0.1:2379
 timeout: 5

Still, there is no such parameter for etcd. Please, refer [Patroni docs](https://patroni.readthedocs.io/en/latest/SETTINGS.html#etcd) - it is what `SPILO_CONFIGURATION` is setting.


> that's also hard-coded, 3 timeouts of 3 seconds

It is actually not: https://github.com/zalando/patroni/blob/master/patroni/dcs/etcd.py#L111-L136

```
per_node_timeout /= per_node_retries
```
so it turns 10 / 3 = 3,(3), where 10 is the default `retry_timeout`.
`retry_timeout` in its turn is the parameter you can influence in Patroni configuration.

**Comment by gabrielmocan** [comment]
@hughcapet thanks for the clarification. Can I then alter `retry_timeout` via `SPILO_CONFIGURATION` env?

**Comment by hughcapet** [comment]
yes. as I said, it is a Patroni parameter, for bootstrap it can be set via `SPILO_CONFIGURATION`

```
SPILO_CONFIGURATION='{"bootstrap": {"dcs": {"retry_timeout": <your_value> }}}'
```
afterwards - you can alter it using patronictl/rest api

**Comment by hughcapet** [comment]
but before tuning this parameter also make sure you understand the connection between it and both `loop_wait` and `ttl` parameter (rule is: `ttl >= loop_wait + retry_timeout * 2`)

**Comment by gabrielmocan** [comment]
Many thanks, will do some tuning. I'm closing this issue.
