### ISSUE TITLE
No core dump generated when postgres or other process crashes.

### ISSUE THREAD

**Issue by mblsf** [zalando/spilo#841]
Seems that no core dump is generated when postgres or other process crashes in the running container.

Please describe how to enable core dumps in the spilo image.

**Comment by hughcapet** [comment]
it is not about Spilo itself but rather about how you configure the running container

e.g. https://stackoverflow.com/questions/28335614/how-to-generate-core-file-in-docker-container

**Comment by mblsf** [comment]
@hughcapet Thanks for the hint.
We are running the image together with postgres-operator in k8s. 
I'll try to find out how to configure core dumps in this environment.
