### ISSUE TITLE
Include parquet_s3_fdw

### ISSUE THREAD

**Issue by ibotty** [zalando/spilo#853]
It would be great to use https://github.com/pgspider/parquet_s3_fdw.

Would you accept a pull request that builds the extension when building spilo?  Unfortunately I won't have time in the near future to package it and get it into `apt.postgresql.org` (pgspider/parquet_s3_fdw#15), I might find time to update spilo to build it locally though.

**Comment by hughcapet** [comment]
I am afraid, no. We are not planning to include more extensions that are not available as packages and need to be built from source.
