### ISSUE TITLE
Question: admin role membership is unclear

### ISSUE THREAD

**Issue by mneverov** [zalando/spilo#862]
I use postgres-operator+spilo+patroni. When I create a database with a default user the following users are created:

```
\du
     Role name     |                         Attributes                         |              Member of
-------------------+------------------------------------------------------------+-------------------------------------
 admin             | Create DB, Cannot login                                    | {cron_admin,myuser}
 cron_admin        | Cannot login                                               | {}
 myuser            | Create role, Create DB                                     | {}
 postgres          | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 robot_zmon        | Cannot login                                               | {}
 standby           | Replication                                                | {}
```

Question: why `admin` is a member of newly created users?
I would expect be the other way around: newly created users are members of admin role so they inherit `CREATEDB` privilege.
I don't get what benefits it gives to give membership of my user to admin , could you please clarify?

**Comment by hughcapet** [comment]
How do you create 'myuser' role?

**Comment by hughcapet** [comment]
then it is definitely not the right place to ask this question. Seems, you even know the link:)

**Comment by mneverov** [comment]
I mean `admin` is a role created by [spilo](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/post_init.sh#L17). What is the idea behind it? What tasks it is supposed to do?
Will ask about ownership in postgres-operator proj, thx.
