### ISSUE TITLE
move all dep build to dependencies-builder in dockerfile

### ISSUE THREAD

**Issue by zlcnju** [zalando/spilo#870]
Although the dependencies-builder is included in the Dockerfile [link](https://github.com/zalando/spilo/blob/bb02a3a0a9da730de7a2da7da10a08b500fa7eed/postgres-appliance/Dockerfile#L18), there are some builds present in the base.sh script [link](https://github.com/zalando/spilo/blob/master/postgres-appliance/build_scripts/base.sh). These builds may introduce unnecessary packages, potentially exposing security vulnerabilities. I'm curious to know the reasons behind not consolidating all the builds in the dependencies-builder.

**Comment by hughcapet** [comment]
There is cleanup done in base.sh. But if you suppose something should and can be moved across stages, you are welcome to submit a PR providing these changes
