### ISSUE TITLE
./run: 21: ulimit: error setting limit (Operation not permitted)

### ISSUE THREAD

**Issue by gaozhenhai** [zalando/spilo#881]
spilo image: spilo-14:2.1-p6
securityContext value  as follows：
 
<img width="528" alt="image" src="https://github.com/zalando/spilo/assets/13032378/4c363f91-dfbf-4191-a9e1-d53e3e03cb89">

But, spilo pod run failed, error as follows:
<img width="997" alt="image" src="https://github.com/zalando/spilo/assets/13032378/f3af0819-65fc-458e-a2b1-57d7a43d578c">

spilo pod do not have permission to run “ulimit -c unlimited”，on kubernetes，What kind of setup is needed？

**Comment by hughcapet** [comment]
Your pod lacks the capability for that operation not having 'unlimited' as the default value. So you can, for example, run the container in the privileged mode or add `CAP_SYS_RESOURCE` capability to it if it suits you security policies.

**Comment by gaozhenhai** [comment]
> Your pod lacks the capability for that operation not having 'unlimited' as the default value. So you can, for example, run the container in the privileged mode or add `CAP_SYS_RESOURCE` capability to it if it suits you security policies.

Thank you very much. After I added the SYS_RESOURCE policy, it is working fine
