### ISSUE TITLE
What's the motivation for the 10GB limit for WAL restore?

### ISSUE THREAD

**Issue by andyndang** [zalando/spilo#886]
I'm encountering this issue and it seems there's a hard coded value for WAL restore limit of around 10GB. Any reason why? 

https://github.com/zalando/spilo/blob/01064d6215aac00c1f4eab75cfa1dcfc216f767b/postgres-appliance/scripts/wale_restore.sh#L5

**Comment by hughcapet** [comment]
it is actually configurable https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst?plain=1#L50
