### ISSUE TITLE
[Feature Request] Add pgvector extension to spilo

### ISSUE THREAD

**Issue by drivebyer** [zalando/spilo#894]
I noticed that the Spilo image has loaded some custom extensions, such as bg_mon and pg_permissions, which enhance the functionality of PostgreSQL. 

I propose to add a new extension, pgvector(https://github.com/pgvector/pgvector). This extension can add a vector type in PostgreSQL to store vector data, thus equipping PostgreSQL with the capability to store vector data.

**Comment by wilsonwu** [comment]
For AI would, it is a good feature we need.

**Comment by hughcapet** [comment]
Yes, I think the extension will be added in the near future. Or you can also create a PR if you want to hurry things up

**Comment by drivebyer** [comment]
> Yes, I think the extension will be added in the near future. Or you can also create a PR if you want to hurry things up

I am glad to. I will do it next month.

**Comment by drivebyer** [comment]
pg_vector available since ghcr.io/zalando/spilo-15:3.1-p1
