### ISSUE TITLE
Security Vulnerabilities Found

### ISSUE THREAD

**Issue by jayantb-95** [zalando/spilo#985]
- **Which image of the operator/spilo are you using?** 
	registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
	ghcr.io/zalando/spilo-15:3.0-p1

- **Where do you run it ?**
	Bare Metal Openshift

- **Are you running Postgres Operator in production?**
	yes

- **Type of issue?** 
	Security Vulnerability

[rdbms_vulnerabilities_github.xlsx](https://github.com/zalando/spilo/files/14567432/rdbms_vulnerabilities_github.xlsx)

Hi Team Zalando,
We've deployed the postgres-operator in our environment with slight modification of splitting this single repo into 3 different helm charts, mainly CRDs, Operator & the Cluster
We're reported various security vulnerabilities as part of the security scan (excel sheet attached), with reference to the CVE-ID respectively.

**Comment by hughcapet** [comment]
the latest image is `ghcr.io/zalando/spilo-15:3.2-p1`

https://github.com/zalando/spilo/pkgs/container/spilo-15

**Comment by dpmillerau** [comment]
github actually lists 3.0-p1 as the latest release.

**Comment by hughcapet** [comment]
we;ve stopped publishing releases. only building new images from time to time
